#Import

In [ ]:
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, pipeline
import pandas as pd

#to remove warnings when using microsoft/Phi-3.5-mini-instruct
import logging
from transformers import logging as transformers_logging

# Only show errors, hide warnings
transformers_logging.set_verbosity_error()

# Model and pipeline definition

In [ ]:
torch.cuda.is_available()

model = AutoModelForCausalLM.from_pretrained("microsoft/Phi-3.5-mini-instruct",
                                              device_map="auto",
                                              torch_dtype="auto",
                                              trust_remote_code=False)

tokenizer = AutoTokenizer.from_pretrained("microsoft/Phi-3.5-mini-instruct",
                                          trust_remote_code=True)

pipe = pipeline("text-generation",
                model=model,
                tokenizer=tokenizer,
                max_new_tokens=300,
                max_length=300,
                temperature=0.2, #range [0,1]
                top_p=1) #range [0,1], usually between .8 and 1

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json: 0.00B [00:00, ?B/s]

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/195 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/195 [00:00<?, ?B/s]

configuration_phi3.py: 0.00B [00:00, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

tokenizer.model:   0%|          | 0.00/500k [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/306 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

# Datasets loading

In [ ]:
#paths samuel
topics_path = "/content/drive/MyDrive/Uni/aa2425/TLN/DiCaro/5/topic_lab_4.csv"
definitions_path = "/content/drive/MyDrive/Uni/aa2425/TLN/DiCaro/5/def.csv"

#general paths
#topics_path = "/content/drive/MyDrive/ ... /5/topic_lab_4.csv"
#definitions_path = "/content/drive/MyDrive/ ... /5/def.csv"

from google.colab import drive
drive.mount("/content/drive", force_remount=True)

Mounted at /content/drive

In [ ]:
topics = pd.read_csv(topics_path)
definitions = pd.read_csv(definitions_path)
definitions = definitions.drop("Unnamed: 0",axis=1).drop("Termine",axis=1)

In [ ]:
topics.head()

,Topic,Count,Name,Representation,Representative_Docs
0,-1,22961,-1_of_the_in_and,"['of', 'the', 'in', 'and', 'to', 'with', 'that...",['Clinical signs of pulmonary congestion indic...
1,0,4005,0_cancer_tumor_cells_expression,"['cancer', 'tumor', 'cells', 'expression', 'ce...",['IL-6 was significantly associated with poor ...
2,1,1066,1_asthma_allergic_airway_ige,"['asthma', 'allergic', 'airway', 'ige', 'aller...",['Omalizumab exerts inhibitory effects on airw...
3,2,987,2_pain_propofol_morphine_isoflurane,"['pain', 'propofol', 'morphine', 'isoflurane',...",['The analgesic interaction between intratheca...
4,3,833,3_mutation_gene_mutations_genetic,"['mutation', 'gene', 'mutations', 'genetic', '...",['Our results suggest that genetic variation a...

In [ ]:
definitions.head()

,P1,P2,P3,P4,P5,P6,P7,P8,P9,P10,...,P34,P35,P36,P37,P38,P39,P40,P41,P42,P43
0,Indumento per la parte inferiore del corpo umano,"Indumento per le gambe, diviso per ogni gamba ...",abito indossato sulle gambe,capo di abbigliamento per le gambe,Indumento indossato nella parte inferiore del ...,Indumento per la parte inferiore del corpo che...,Capo indossabile che copre la parte inferiore ...,indumento indossabile da una persona tipicamen...,Indumento che copre le gambe di una persona,Indumento da indossare dalla vita in giù,...,Indumento adibito ad essere indossato nella pa...,Indumento resistente e popolare,abbigliamento fatto di tessuto più o meno sint...,"indumento che si indossa dalla vita in giù, pu...",capo di abbigliamento indossabile nella parte ...,capo di abbigliamento per coprire le gambe,"Vestito, abito, maschile o femminile che copre...",Capo d'abbigliamento indossato sulla parte inf...,NaN,NaN
1,Strumento scientifico per l'osservazione di mi...,Dispositivo ottico o elettronico per ispeziona...,strumento dotato di lenti che permette di visu...,strumento per osservare da vicino cose molto p...,Strumento scientifico utilizzato per ingrandir...,Strumento che permette di ingrandire oggetti e...,dispositivo per vedere oggetti visibili solo n...,dispositivo utilizzato per l'analisi e la visi...,Strumento per osservare elementi non visibili ...,Strumento impiegato per facilitare la visualiz...,...,Strumento che consente di osservare elementi n...,strumento che ingranisce oggetti piccoli,strumento scientifico con scopo di ricerca su ...,strumento per la visione ingrandita di oggetti...,strumento scientifico per osservare oggetti no...,un dispositivo scientifico che utilizza lenti ...,strumento generalmente utilizzato a scopi di r...,Strumento utilizzato per vedere oggetti di pic...,NaN,NaN
2,Situazione potenzialmente rischiosa,Situazione in cui si teme per la propria o alt...,condizione che può causare danni alle persone ...,Evento che minaccia la sicurezza di una persona,Situazione dove é minacciata la sicurezza di u...,Situazione in cui è a rischio l’incolumità di ...,Evento in cui ci si la propria vita si sente m...,situazione che compromette la sicurezza di un ...,situazione che minaccia la sicurezza di un sog...,Situazione in cui l’incolumità della persona è...,...,Situazione in cui l'incolumità fisica o psicol...,situazione che può provocare sofferenza,situazioni in cui viene messa a rischio la vit...,situazione in cui si rischia di subire una qua...,percezione di una situazione di minaccia,situazione di rischio,situazione in cui si teme di essere esposti a ...,E' una caratteristica che definisce situazioni...,NaN,NaN
3,Strategia di ricerca nello spazio degli stati,Strategia di ricerca che permette di stimare i...,regola che permette di approssimare una soluzi...,NaN,Funzione che stima la distanza dallo stato att...,Strategia adottata durante la risoluzione di u...,Funzione per approssimare un comportamento,ipotesi assunta nella ricerca scientifica e me...,Metodologia di ricerca di fatti o verità,Metedologia per trovare soluzione migliore ris...,...,Criterio utilizzato al fine dell'ottenimento d...,scorciatoia mentale utilizzata per risolvere p...,stima che viene utilizzata per calcolare i cos...,approssimazione fatta rispetto a un insieme di...,funzione che permette di calcolare un risultat...,un insieme di metodi di ricerca che facilitano...,strategia o procedimento per ricercare element...,E' un valore di stima per difetto,NaN,NaN

# Tasks

## Labelling

### Zero-shot

In [ ]:
#[0] -> zero_shot_istruzioni
#[1] -> zero_shot_iterativo
#[2] -> few_shot_istruzioni
#[3] -> few_shot_iterativo
#[4] -> chain_of_thought
labelling_results = [[],[],[],[],[]]

**Prompting basato su istruzioni**

In [ ]:
for n in range(1,len(topics)):
  zero_shot_prompt = [{
                      "role": "system",
                      "content": "You're a topic labeller system. Given a name, representation and representative document you generate the related label."

                    },
                    {
                      "role": "user",
                      "content": f"name: {topics.loc[n]["Name"]}, representation: {topics.loc[n]["Representation"]}, representative document: {topics.loc[n]["Representative_Docs"]}.\
                                  The label must have a max of 5 words, summarizing the main representative document objectives with respect to representation words.\
                                  The output should be concise and easily interpretable.\
                                  There must be only the label as the ouput, nothing more.",
                    }
                  ]
  output = pipe(zero_shot_prompt)
  #print(output[0]["generated_text"]) #prompt + answer
  print(f"Topic: {n}, label: {output[0]["generated_text"][2]["content"]}") #just the answer
  labelling_results[0].append(output[0]["generated_text"][2]["content"])

Topic: 1, label:  Breast cancer prognosis and treatment response prediction
Topic: 2, label:  Anti-IgE therapy reduces airway inflammation in allergic asthma
Topic: 3, label:  Propofol-Analgesia-Spinal Anesthesia
Topic: 4, label:  Genetic susceptibility in metabolic syndrome and FMTC mutations
Topic: 5, label:  Endometriosis impact on pregnancy outcomes and ART pregnancy risks
Topic: 6, label:  Prognostic Lymph Node Metastasis Chemotherapy Impact
Topic: 7, label:  Retinal implant effects, ocular complications, visual adaptation, glaucoma risk, retinal recovery
Topic: 8, label:  Intestinal mucosal colitis treatment in IBD patients
Topic: 9, label:  Cardiac Ischemia Reperfusion Protection
Topic: 10, label:  miRNA expression prognostic therapeutic cancer
Topic: 11, label:  CKD-related arterial stiffness risk in coronary patients
Topic: 12, label:  HIV infection, CD4 impairment, antiretroviral management
Topic: 13, label:  Schizophrenia, Social Cognition, Genetic Links, Mitochondrial Dysfunction, Oxytocin Treatment
Topic: 14, label:  Knee OA load analysis and ACL repair impacts
Topic: 15, label:  HCV treatment and NK cell activation
Topic: 16, label:  Plant TOR function study, N response regulation, Sulfur metabolism drought impact
Topic: 17, label:  Implant surface effects on bone stability and complications
Topic: 18, label:  LV dysfunction, echocardiography prognosis, infarct size assessment
Topic: 19, label:  Evidence-based care improvement research
Topic: 20, label:  Bladder dysfunction recovery assessment
Topic: 21, label:  Depression progression prediction in MCI and AD risk
Topic: 22, label:  Weight management through dietary behavior
Topic: 23, label:  Notch signaling in cell fate and differentiation
Topic: 24, label:  Prevent renal tubular injury, fibrosis, inflammation
Topic: 25, label:  Heart failure prognosis and NT-proBNP monitoring
Topic: 26, label:  Cartilage degradation, chondrocyte apoptosis, matrix organization, OA pathology, cartilage repair strategies.
Topic: 27, label:  Statins' endothelial effects and angiogenesis modulation
Topic: 28, label:  MRSA Carrier Prevention and Screening
Topic: 29, label:  Diet-induced obesity prevention, fatty acid regulation
Topic: 30, label:  Liver regeneration, hepatocyte therapy, apoptosis reduction, fibrosis treatment, cell transplantation
Topic: 31, label:  Aβ prothrombotic mechanism in AD dementia
Topic: 32, label:  RA susceptibility polymorphisms study
Topic: 33, label:  Bile-induced liver injury, inflammation, sepsis prevention
Topic: 34, label:  AF ablation outcomes in atrial size, time, recurrence
Topic: 35, label:  RA synovial inflammation biomarkers IL-29 dysregulation
Topic: 36, label:  Acute pancreatitis treatment strategies
Topic: 37, label:  High-frequency ventilation improvement, right ventricular function monitoring
Topic: 38, label:  Preterm Neonatal Birth Care & Outcomes
Topic: 39, label:  Prostate cancer prognosis, gene biomarkers, therapeutic targets
Topic: 40, label:  H. pylori infection, gastric cancer, CagA strains, risk reduction, tolerance development
Topic: 41, label:  Prostate cancer risk prediction, PSA levels, biopsy correlation
Topic: 42, label:  Bone regeneration, MSCs, BMP-2, osteogenesis, tissue engineering
Topic: 43, label:  Exercise, Bone Mass, Sarcopenia, Osteoporosis, Muscle Strength
Topic: 44, label:  Cochlear implant speech recognition improvement
Topic: 45, label:  Sperm quality, antibodies, fertilization impact
Topic: 46, label:  GH secretion, ghrelin levels, IGF-I treatment, obesity, GHD subjects
Topic: 47, label:  Acute rejection markers, donor cytokines, immunosuppression impact.
Topic: 48, label:  NAFLD, insulin resistance, diabetes, diet impact, liver health improvement
Topic: 49, label:  Predictors of AED resistance, seizure patterns, HFO analysis
Topic: 50, label:  Angiotensin II effects without endothelium mediated by type 2 receptors
Topic: 51, label:  Insomnia, sleep quality, sleep duration, sleep disturbances, obesity association
Topic: 52, label:  Pregnancy, breastfeeding, offspring weight, gestational disorders, diabetes risk
Topic: 53, label:  Hox gene evolution and regulatory interactions
Topic: 54, label:  COPD management and CPAP effectiveness in emphysema patients
Topic: 55, label:  Folate, Homocysteine, Vitamin B12, Hyperhomocysteinemia, Plasma Study Objectives
Topic: 56, label:  GERD treatment, esophageal pH improvement, PPI reduction
Topic: 57, label:  Alcohol consumption, preference, CTA, adolescent rats, early exposure
Topic: 58, label:  SLE activity, anti-C1q antibodies, disease activity, nephritis, autoantibodies
Topic: 59, label:  Hypoglycemia, hyperglycemia, mortality risk, glucose management, cardiac surgery patients
Topic: 60, label:  Epigenetic methylation suppression in neuroblastoma
Topic: 61, label:  Smoking cessation and nicotine dependence prediction
Topic: 62, label:  Periodontal inflammation cardiovascular linkage study
Topic: 63, label:  PAR4 inhibition thrombosis prevention
Topic: 64, label:  Burn injury resuscitation outcomes and gender disparities in HRQoL
Topic: 65, label:  Kidney Transplant Donor Selection and Outcomes
Topic: 66, label:  Vitamin D supplementation effects on BMI and deficiency in women and men.
Topic: 67, label:  Integrated malaria control and community management
Topic: 68, label:  Atherosclerosis, MCP-1, Macrophage, Therapeutic Target, MKP-1 Deficiency
Topic: 69, label:  Colonoscopy polyp detection and adenoma risk assessment
Topic: 70, label:  Fall prevention in older adults, self-efficacy, modifiable risk factors
Topic: 71, label:  Motor cortical excitability alterations in sensorimotor integration
Topic: 72, label:  Carotenoid biosynthesis diversification research
Topic: 73, label:  Adiponectin, insulin resistance, obesity markers
Topic: 74, label:  CMV vaccine efficacy, liver fibrosis, H5N1 protection
Topic: 75, label:  Curcumin immune modulation and cell apoptosis
Topic: 76, label:  GLP-1 receptor cardiovascular effects, glucagon secretion regulation
Topic: 77, label:  Vancomycin SSI prevention, postoperative wound management
Topic: 78, label:  CYP Polymorphisms Affect Drug Metabolism and Dosing
Topic: 79, label:  Carotid revascularization safety in octogenarians and recurrent stenosis treatment
Topic: 80, label:  Treg cell imbalance, IL-17, IL-10, Foxp3, ICOS signaling
Topic: 81, label:  PCOS, insulin resistance, hyperandrogenism, metabolic levels
Topic: 82, label:  Stem cell therapy for heart repair and regeneration
Topic: 83, label:  HPV screening, cervical cancer prevention, women's health
Topic: 84, label:  Platelet storage, cytokine levels, prestorage leukoreduction
Topic: 85, label:  Trauma care improvement, patient outcomes, SOP efficiency
Topic: 86, label:  Peer-based clinical skill learning and assessment
Topic: 87, label:  Sildenafil erectile dysfunction cardiovascular safety
Topic: 88, label:  PET imaging for lung injury diagnosis and metastasis detection
Topic: 89, label:  Migraine with Aura and Bipolarity Association
Topic: 90, label:  Waist circumference cardiovascular risk assessment
Topic: 91, label:  Heroin-seeking behavior, drug relapse prevention, cholinergic transmission, SSM pharmacological agent, BLA neural circuitry
Topic: 92, label:  Allopurinol reduces vascular oxidative stress, affects PTH secretion
Topic: 93, label:  HDL Cholesterol Protection Against CAAD and RA Cardiovascular Risk
Topic: 94, label:  Prevent postoperative bleeding, reduce transfusion need
Topic: 95, label:  MS Fatigue Impact on QoL and Treatment Response
Topic: 96, label:  HIF-1alpha tumor therapy indication
Topic: 97, label:  Air pollution impact on lung health and cardiovascular risk
Topic: 98, label:  Enhance islet transplantation survival and function
Topic: 99, label:  Autonomic modulation in cardiovascular health and stroke risk
Topic: 100, label:  Insulin resistance, pioglitazone, glucose control, adipose tissue, diabetes management
Topic: 101, label:  Parathyroidectomy with sestamibi imaging
Topic: 102, label:  Postural sway rehabilitation pain assessment
Topic: 103, label:  Cannabinoid receptor signaling and therapeutic implications
Topic: 104, label:  Phospholipid depletion, alcohol-induced liver injury prevention, SAMe restoration
Topic: 105, label:  DHEA, Insulin, Myostatin, Testosterone, Diabetes
Topic: 106, label:  Thyroid hormone levels, TSH impact on health, age-related TSH adjustment
Topic: 107, label:  CD8 T cells, GrzB, CpG-ODN, regulatory T cells, cytokine regulation
Topic: 108, label:  PTSD, Childhood Trauma, Stress Reactivity, Inflammatory Cytokines, PTSD Pathophysiology
Topic: 109, label:  Peritoneal dialysis transport enhancement, lymphatic absorption increase, saline inefficacy, pyruvate alternative.
Topic: 110, label:  Heat impact on exercise performance and thermoregulation
Topic: 111, label:  MRI predicts RA radiographic progression and remission failure
Topic: 112, label:  Resveratrol Metabolites Tumor Regression, Apoptosis Induction
Topic: 113, label:  Prevent leakage, enhance anastomosis sealing post-surgery
Topic: 114, label:  Melanoma liver resection safety and efficacy
Topic: 115, label:  Reduce alert fatigue, prioritize therapeutic groups
Topic: 116, label:  Fluid balance impacts septic mortality, catecholamine choice varies
Topic: 117, label:  Femoral stem fixation, nonunion prevention, hip resection success

**Prompting iterativo**

In [ ]:
for n in range(1,len(topics)):
  zero_shot_prompt = [{
                      "role": "system",
                      "content": "You're a topic labeller system. Given a name, representation and representative document you generate the related label by following the instructions."

                    },
                    {
                      "role": "user",
                      "content": f"name: {topics.loc[n]["Name"]}, representation: {topics.loc[n]["Representation"]}, representative document: {topics.loc[n]["Representative_Docs"]}.\
                                  Provide only the label as output, nothing else.\
                                  Instructions:\
                                  1. Read the representative document and extract a brief summary of the main object.\
                                  2. Compare the words inside the extracted informations with the words inside the representation given as input and redefine the expressions using the latter ones when possible.\
                                  3. Create a label, of max 5 word, that conceptualizes such content. Such label does not have to be syntactycally correct but rather interpretable.\
                                  4. If the label if longer than 5 words discard it and get back to instruction 3.",
                    }
                  ]
  output = pipe(zero_shot_prompt)
  #print(output[0]["generated_text"]) #prompt + answer
  print(f"Topic: {n}, label: {output[0]["generated_text"][2]["content"]}") #just the answer
  labelling_results[1].append(output[0]["generated_text"][2]["content"])

Topic: 1, label:  Breast cancer prognosis markers
Topic: 2, label:  Allergic Asthma Airway Ige Treatment
Topic: 3, label:  Spinal anesthesia analgesia propofol
Topic: 4, label:  Gene Mutations Risk Assessment
Topic: 5, label:  Endometriosis Pregnancy Outcomes
Topic: 6, label:  Chemotherapy Prognosis Lymph Node Metastasis
Topic: 7, label:  Retinal Implant Complications
Topic: 8, label:  Intestinal IBD Gut Colitis
Topic: 9, label:  Cardiac Ischemia Reperfusion Protection
Topic: 10, label:  miRNA prognostic cancer therapy
Topic: 11, label:  CKD_coronary_risk_stiffness
Topic: 12, label:  HIV Surgical Management
Topic: 13, label:  Schizophrenia-related disorders and treatments
Topic: 14, label:  Knee ACL Tendon Joint OA
Topic: 15, label:  HCV treatment strategy
Topic: 16, label:  Plant TOR Functions
Topic: 17, label:  Dental implant stability and bone changes
Topic: 18, label:  LV myocardial CRT ventricular patients echocardiography
Topic: 19, label:  Care Meta-Reviews Physician Experience
Topic: 20, label:  Bladder Incontinence Analysis
Topic: 21, label:  Depressive Ad Recovery Impact
Topic: 22, label:  Dietary behavior impact on weight management
Topic: 23, label:  Notch signaling in cell fate and differentiation
Topic: 24, label:  Renal Tubular Injury Prevention
Topic: 25, label:  Heart Failure Prognostic Marker
Topic: 26, label:  Chondrocyte Differentiation in Articular Cartilage
Topic: 27, label:  Statin effects on endothelial cells
Topic: 28, label:  MRSA Carrier Prevention
Topic: 29, label:  Insulin-fat-adipose-diet-regulation
Topic: 30, label:  Liver regeneration hepatocytes
Topic: 31, label:  Aβ prothrombotic AD pathology
Topic: 32, label:  HLA-CDR Polymorphism Susceptibility
Topic: 33, label:  Bile-induced liver injury label
Topic: 34, label:  Aortic Valve Ablation Outcomes
Topic: 35, label:  RA inflammatory synovial arthritis IL-29 TNF mtx joints
Topic: 36, label:  Pancreatic Acute ERCP
Topic: 37, label:  High-frequency ventilation mitral valve
Topic: 38, label:  Preterm Neonatal Birth Care
Topic: 39, label:  Prostate Cancer Androgen Prostatic Cells
Topic: 40, label:  H. pylori eradication impacts gastric diseases
Topic: 41, label:  Prostate Cancer Diagnosis
Topic: 42, label:  Bone regeneration MSCs BMPs Synthetic substitutes
Topic: 43, label:  Exercise-related sarcopenia management
Topic: 44, label:  Cochlear Implant Speech Perception
Topic: 45, label:  Sperm quality study
Topic: 46, label:  GH secretion and ghrelin levels in GHD subjects
Topic: 47, label:  Acute rejection allografts
Topic: 48, label:  NAFLD insulin resistance diabetes coffee diet
Topic: 49, label:  Seizure-onset patterns and HFO analysis
Topic: 50, label:  Angiotensin II type 2 receptor involvement
Topic: 51, label:  Insomnia Sleep Quality
Topic: 52, label:  Gestational Milk Influence on Offspring Weight
Topic: 53, label:  ProtoHox cluster origin
Topic: 54, label:  COPD management and CPAP effectiveness
Topic: 55, label:  Folate-Homocysteine-Vitamin B12-Reduction-Study
Topic: 56, label:  Esophageal pH GERD treatment
Topic: 57, label:  Alcohol consumption and preference modeling
Topic: 58, label:  SLE autoantibodies activity
Topic: 59, label:  Glucose-related mortality in women postmenopausal HRT and diabetes patients.
Topic: 60, label:  Methylation Promoter Epigenetics Neuroblastoma
Topic: 61, label:  Smoking cessation and nicotine replacement
Topic: 62, label:  Periodontal inflammation cardiovascular risk
Topic: 63, label:  Platelet PAR4 inhibition
Topic: 64, label:  Burn Injury Resuscitation Care
Topic: 65, label:  Kidney Transplant Success Factors
Topic: 66, label:  Vitamin D deficiency study
Topic: 67, label:  Malaria control integration
Topic: 68, label:  Atherosclerotic plaque development
Topic: 69, label:  Colorectal polyp detection
Topic: 70, label:  Falls Prevention in Older Adults
Topic: 71, label:  Motor Cortical Visual Excitability
Topic: 72, label:  Carotenoid Biosynthesis Research
Topic: 73, label:  Adiponectin-Insulin-Obesity-Inflammation
Topic: 74, label:  CMV vaccine efficacy and liver fibrosis
Topic: 75, label:  Curcumin immune modulation
Topic: 76, label:  GLP-1 and glucagon regulation in cardiovascular system
Topic: 77, label:  Postoperative SSI Vancomycin Reduction
Topic: 78, label:  CYP Polymorphisms Pharmacokinetics Interaction
Topic: 79, label:  Carotid Revascularization Outcomes
Topic: 80, label:  Treg cells, IL-17, Foxp3, antibodies, production
Topic: 81, label:  PCOS hyperandrogenism insulin levels
Topic: 82, label:  Stem cell therapy for heart repair
Topic: 83, label:  HPV screening impact on cervical cancer in Pakistani women
Topic: 84, label:  Platelet Storage PCS Cytokines
Topic: 85, label:  Trauma MRI Patient Care
Topic: 86, label:  Peer-based Clinical Skills Learning
Topic: 87, label:  Erectile Dysfunction Sildenafil Study
Topic: 88, label:  PET-CT for lung injury assessment
Topic: 89, label:  Migraine Aura Study
Topic: 90, label:  Waist Circumference BMI Risk Assessment
Topic: 91, label:  Drug-seeking behavior and relapse prevention
Topic: 92, label:  Allopurinol-endothelial function
Topic: 93, label:  HDL-3 and Cardiovascular Risk
Topic: 94, label:  Postoperative Heparin Graft Bleeding Control
Topic: 95, label:  MS Fatigue QoL Improvement
Topic: 96, label:  HIF-1alpha inhibition therapy
Topic: 97, label:  Air Pollution Impact on Workers' Health
Topic: 98, label:  Islet Transplantation Efficacy Improvement
Topic: 99, label:  Autonomic Heart HRV Study
Topic: 100, label:  Insulin-pioglitazone-metformin-effect-diabetes
Topic: 101, label:  Parathyroidectomy Sestamibi Scan
Topic: 102, label:  Postural Sway Rehabilitation Pain
Topic: 103, label:  Cannabinoid receptor signaling
Topic: 104, label:  Phospholipid restoration in alcoholic liver
Topic: 105, label:  DHEA_Myostatin_Insulin_Diabetes_Muscle
Topic: 106, label:  Thyroid Hormone Disorders
Topic: 107, label:  TLR3-CD8-GrzB-CpG-Regulatory-Skin-Inflammation
Topic: 108, label:  PTSD childhood trauma stress
Topic: 109, label:  Peritoneal transport modification
Topic: 110, label:  Heat Exercise Performance Water Temperature
Topic: 111, label:  MRI remission wrist RA progression
Topic: 112, label:  Resveratrol Metabolites and Islet Effects
Topic: 113, label:  Anastomotic leakage prevention
Topic: 114, label:  Melanoma Hepatectomy Liver Resection
Topic: 115, label:  Drug interaction alert prioritization
Topic: 116, label:  Fluid therapy mortality septic shock catecholamines cardiac
Topic: 117, label:  Femoral Screw Fracture Management

### Few-shot

**Few-shot examples**

In [ ]:
example1 = {"Representative_Docs": "A 65-year-old patient arrives at the ER complaining of a sudden onset of shortness of breath and a persistent productive cough. Physical examination reveals wheezing in the lower lobes, and a history of COPD is noted in their chart.",
             "representation":      "dyspnea, wheezing, sputum, airflow, chronic, pulmonary",
             "label":               "Chronic Obstructive Pulmonary Exacerbation"}

example2 = {"Representative_Docs": "Following a successful appendectomy, the patient is monitored in the PACU. The surgical site is checked for drainage or signs of infection. The nurse administers IV analgesics for pain management and records the vital signs every four hours.",
             "representation":      "post-op, incision, sutures, recovery, sterile, analgesia",
             "label":               "Post-Surgical Care & Wound Monitoring"}

example3 = {"Representative_Docs": "A patient with a family history of Type 2 Diabetes undergoes a fasting glucose test. The results show an elevated A1c level of 7.2%. The physician discusses starting Metformin and refers the patient to a dietician for glycemic counseling.",
             "representation":      "insulin, glucose, metabolic, hyperglycemia, A1c, endocrine",
             "label":               "Diabetes Mellitus Diagnosis & Management"}

**Prompt basato su istruzioni**

In [ ]:
for n in range(1,len(topics)):
  few_shot_prompt = [{
                      "role": "system",
                      "content": "You're a topic labeller system.\
                                  Given a name, representation and representative document you generate the related label.\
                                  Use the given examples as guides to help you produce better outputs."

                    },
                    {
                      "role": "user",
                      "content": f"name: {topics.loc[n]["Name"]}, representation: {topics.loc[n]["Representation"]}, representative document: {topics.loc[n]["Representative_Docs"]}.\
                                  The label must contain max 5 words, capturing the main representative document objective with respect to representation words.\
                                  The output should be concise and easily interpretable.\
                                  There must be only the label as the ouput, nothing more.\
                                  Examples:\
                                  example1: representative document:{example1["Representative_Docs"]}, representation: {example1["representation"]}, label: {example1["label"]}.\
                                  example2: representative document:{example2["Representative_Docs"]}, representation: {example2["representation"]}, label: {example2["label"]}.\
                                  example3: representative document:{example3["Representative_Docs"]}, representation: {example3["representation"]}, label: {example3["label"]}.",
                    }
                  ]
  output = pipe(few_shot_prompt)
  #print(output[0]["generated_text"]) #prompt + answer
  print(f"Topic: {n}, label: {output[0]["generated_text"][2]["content"]}") #just the answer
  labelling_results[2].append(output[0]["generated_text"][2]["content"])

Topic: 1, label:  Breast Cancer Prognostic Markers
Topic: 2, label:  Allergic Asthma Inflammation Reduction
Topic: 3, label:  Anesthetic Pain Management
Topic: 4, label:  Genetic Variants & Metabolic Syndrome Risk
Topic: 5, label:  Pregnancy Endometriosis Complications
Topic: 6, label:  Lymph node involvement & chemotherapy timing
Topic: 7, label:  Ocular Complications & Retinal Adaptation
Topic: 8, label:  Intestinal Colitis Relapse Prediction & Treatment
Topic: 9, label:  Ischemic Heart Reperfusion Protection
Topic: 10, label:  miRNA expression, cancer therapy, prognostic biomarker, label: miRNA Therapeutic Potential.
Topic: 11, label:  CKD-related arterial stiffness
Topic: 12, label:  HIV Infection & Surgical Outcomes
Topic: 13, label:  Schizophrenia Social Cognition Impacts
Topic: 14, label:  ACL Tear & Knee Kinematics
Topic: 15, label:  Hepatitis Viral Infection & NK Cells
Topic: 16, label:  Plant TOR Functions & Drought Response
Topic: 17, label:  Implant Bone Level Changes
Topic: 18, label:  LV Dysfunction & Echocardiography Analysis
Topic: 19, label:  Care Meta-Analysis Quality Assessment
Topic: 20, label:  Bladder Incontinence, Urinary Dysfunction, Sphincter Control, Detrusor Activity, Prolapse Management
Topic: 21, label:  Depression Progression & Stroke Recovery
Topic: 22, label:  Dietary Intervention & Weight Management
Topic: 23, label:  Notch signaling in lung development and cell fate
Topic: 24, label:  Renal Tubular Injury Prevention
Topic: 25, label:  Heart Failure Prognosis & NT-proBNP
Topic: 26, label:  Cartilage Degradation & Chondrocyte Role
Topic: 27, label:  Statin Endothelial Effects
Topic: 28, label:  MRSA Colonization & Infection Control
Topic: 29, label:  Obesity & Dietary Fat Regulation
Topic: 30, label:  Liver Regeneration & Fibrosis Treatment
Topic: 31, label:  Aβ-induced Coagulation in AD
Topic: 32, label:  HLA-CD Polymorphisms RA Susceptibility
Topic: 33, label:  Bile-induced liver injury & inflammation
Topic: 34, label:  Aortic Valve Ablation Outcomes
Topic: 35, label:  Synovial Arthritis Inflammation & IL-29 Dysregulation
Topic: 36, label:  Acute Pancreatitis Treatment & NF-κB Inactivation
Topic: 37, label:  Ventilation Peep Valve Mitral High-Frequency
Topic: 38, label:  Preterm Neonatal Care & Auditory Screening
Topic: 39, label:  Prostate Cancer Androgen Influence
Topic: 40, label:  H. pylori Eradication & Gastric Health
Topic: 41, label:  Prostate Cancer Risk Assessment
Topic: 42, label:  Osteogenic MSCs BMP Healing Tissue
Topic: 43, label:  Exercise-induced Sarcopenia Management
Topic: 44, label:  Cochlear Implant Performance & Noise Recognition
Topic: 45, label:  Sperm Quality & Genetic Defects
Topic: 46, label:  GH Secretion & Ghrelin Levels
Topic: 47, label:  Acute Rejection, Donor IL-6, Kidney Transplantation
Topic: 48, label:  Insulin Resistance & NAFLD Diabetes Risk
Topic: 49, label:  Seizure Onset Patterns & HFO Analysis
Topic: 50, label:  Endothelial Damage, Angiotensin II, Losartan, Receptor, Inhibition, Label: Endothelial Angiotensin II Inhibition
Topic: 51, label:  Insomnia, Sleep Quality, Osteoporosis Risk
Topic: 52, label:  Birth Weight & Breastfeeding Diabetes Risk
Topic: 53, label:  Hox Gene Evolution & Regulation
Topic: 54, label:  COPD Management & CPAP Therapy
Topic: 55, label:  Folate Deficiency & Homocysteine Reduction
Topic: 56, label:  Esophageal pH & GERD Management
Topic: 57, label:  Alcohol Preference & CTA Development
Topic: 58, label:  SLE Autoantibodies & Activity
Topic: 59, label:  Hypoglycemia Mortality Risk
Topic: 60, label:  Methylation, Hypermethylation, Promoter, Epigenetic, Neuroblastoma
Topic: 61, label:  Smoking Cessation & Nicotine Dependence
Topic: 62, label:  Periodontal Disease & Inflammation
Topic: 63, label:  PAR4 Inhibition Thrombosis Prevention
Topic: 64, label:  Burn Injury Resuscitation & Care
Topic: 65, label:  Kidney Transplantation Risk Assessment
Topic: 66, label:  Vitamin D Deficiency & Supplementation
Topic: 67, label:  Malaria Control & Transmission Reduction
Topic: 68, label:  Atherosclerotic Plaque Development & MCP-1 Role
Topic: 69, label:  Colonoscopy Missed Polyps & Adenomas
Topic: 70, label:  Falls Prevention & Self-Efficacy
Topic: 71, label:  Motor Cortical Excitability Alteration
Topic: 72, label:  Carotenoid Biosynthesis Research
Topic: 73, label:  Obesity-related adipokines & insulin resistance
Topic: 74, label:  CMV Vaccine Efficacy & Liver Fibrosis
Topic: 75, label:  Ototoxicity, Curcumin, Hair Cells, IFN, Apoptosis
Topic: 76, label:  Glucagon Secretion & GLP-2 Interaction
Topic: 77, label:  Postoperative SSI Vancomycin Treatment
Topic: 78, label:  CYP Polymorphisms & Drug Metabolism
Topic: 79, label:  Carotid Revascularization Safety & Outcomes
Topic: 80, label:  Treg cell imbalance, IL-10, IL-17, Foxp3, antibody production, label: Treg Immune Dysregulation.
Topic: 81, label:  PCOS Hyperandrogenism Management
Topic: 82, label:  Cardiac Stem Cell Therapy
Topic: 83, label:  HPV Screening & Cervical Cancer Prevention
Topic: 84, label:  Platelet Storage & Cytokine Levels
Topic: 85, label:  Trauma Injury MRI Diagnosis
Topic: 86, label:  Workplace Learning & Peer Support
Topic: 87, label:  Erectile Dysfunction & Sildenafil Treatment
Topic: 88, label:  Lung Injury & FDG-PET Imaging
Topic: 89, label:  Migraine with Aura and Depression Link
Topic: 90, label:  Waist Obesity Risk Assessment
Topic: 91, label:  Drug-seeking behavior & relapse prevention
Topic: 92, label:  Allopurinol-Endothelial Function Improvement
Topic: 93, label:  HDL Cholesterol & CAAD Protection
Topic: 94, label:  Postoperative Bleeding Prevention & Heparin Use
Topic: 95, label:  MS Fatigue Impact on QoL
Topic: 96, label:  Hypoxic Tumor Response & HIF-1α
Topic: 97, label:  Air Pollution & Respiratory Health
Topic: 98, label:  Islet Transplantation Survival & Function
Topic: 99, label:  Autonomic Heart HRV Dysfunction
Topic: 100, label:  Insulin Therapy & Metabolic Control
Topic: 101, label:  Hyperparathyroidism Surgery Evaluation
Topic: 102, label:  Postural Sway Rehabilitation Pain Management
Topic: 103, label:  Cannabinoid Receptor Signaling & THC Effects
Topic: 104, label:  Phospholipid Depletion & PPC Protection
Topic: 105, label:  Insulin Regulation & Myostatin Expression
Topic: 106, label:  Thyroid Hormone Disorders
Topic: 107, label:  CD8 T cells, GrzB, immune regulation, CpG-ODN, skin inflammation.
Topic: 108, label:  PTSD Vulnerability & Stress Reactivity
Topic: 109, label:  Peritoneal Transport Enhancement
Topic: 110, label:  Heat Ingestion & Exercise Performance
Topic: 111, label:  MRI Progression Prediction in RA
Topic: 112, label:  Resveratrol effects, metabolites, apoptosis, tumor growth, glucose regulation.
Topic: 113, label:  Anastomotic Leakage Prevention & Surgery
Topic: 114, label:  Major Liver Resection Risks & Recurrence
Topic: 115, label:  Drug Interaction Alerts & CDSS Optimization
Topic: 116, label:  Fluid balance, septic shock, mortality risk
Topic: 117, label:  Femoral Screw Nonunion Management

**Prompt iterativo**

In [ ]:
for n in range(1,len(topics)):
  few_shot_prompt = [{
                      "role": "system",
                      "content": "You're a topic labeller system.\
                                  Given a name, representation and representative document you generate the related label.\
                                  Use the given examples as guides to help you produce better outputs by following the instructions."

                    },
                    {
                      "role": "user",
                      "content": f"name: {topics.loc[n]["Name"]}, representation: {topics.loc[n]["Representation"]}, representative document: {topics.loc[n]["Representative_Docs"]}.\
                                  The label must contain max 5 words, capturing the main representative document objective with respect to representation words.\
                                  The output should be concise and easily interpretable.\
                                  There must be only the label as the ouput, nothing more.\
                                  Examples:\
                                  example1: representative document:{example1["Representative_Docs"]}, representation: {example1["representation"]}, label: {example1["label"]}.\
                                  example2: representative document:{example2["Representative_Docs"]}, representation: {example2["representation"]}, label: {example2["label"]}.\
                                  example3: representative document:{example3["Representative_Docs"]}, representation: {example3["representation"]}, label: {example3["label"]}.\
                                  Instructions:\
                                  1. Read the representative document and extract a brief summary of the main object.\
                                  2. Compare the words inside the extracted informations with the words inside the representation given as input and redefine the expressions using the latter ones when possible.\
                                  3. Create a label, of max 5 word, that conceptualizes such content. Such label does not have to be syntactycally correct but rather interpretable.\
                                  4. If the label if longer than 5 words discard it and get back to instruction 3.",
                    }
                  ]
  output = pipe(few_shot_prompt)
  #print(output[0]["generated_text"]) #prompt + answer
  print(f"Topic: {n}, label: {output[0]["generated_text"][2]["content"]}") #just the answer
  labelling_results[3].append(output[0]["generated_text"][2]["content"])

Topic: 1, label:  Breast Cancer Prognosis & Treatment
Topic: 2, label:  Allergic Asthma Airway Inflammation Omalizumab
Topic: 3, label:  Spinal Anesthesia & Analgesia Management
Topic: 4, label:  Gene Mutations & Metabolic Syndrome Risk
Topic: 5, label:  Endometriosis & Pregnancy Complications
Topic: 6, label:  Lymph node involvement & prognosis prediction
Topic: 7, label:  Retinal Complications & Surgery Recovery
Topic: 8, label:  Intestinal Colitis, IBD, Gut Health, Mucosal Repair, Anti-Colitis Effect.
Topic: 9, label:  Ischemic Heart Protection & Reperfusion
Topic: 10, label:  miRNA Therapeutics & Cancer Prognosis
Topic: 11, label:  CKD Arterial Stiffness Risk
Topic: 12, label:  HIV Infection & Surgical Outcomes
Topic: 13, label:  Schizophrenia Social Cognition Impacts
Topic: 14, label:  ACL repair & knee kinematics
Topic: 15, label:  HCV Infection & NK Activation
Topic: 16, label:  Plant TOR Functions & Drought Response
Topic: 17, label:  Implant Surface & Bone Level Changes
Topic: 18, label:  LV Dysfunction & Sudden Death Risk
Topic: 19, label:  Care Research & Physician Experience
Topic: 20, label:  Bladder Dysfunction & Urodynamic Study
Topic: 21, label:  Depression Progression & Stroke Recovery
Topic: 22, label:  Dietary Intervention & Weight Management
Topic: 23, label:  Notch signaling & lung development
Topic: 24, label:  Renal Tubular Protection & Injury Prevention.
Topic: 25, label:  Heart Failure Prognosis & NT-proBNP
Topic: 26, label:  Cartilage Degradation & Chondrocyte Role
Topic: 27, label:  Statin-induced Endothelial Function Improvement
Topic: 28, label:  MRSA Transmission Prevention
Topic: 29, label:  Obesity Prevention & Dietary Fat Regulation
Topic: 30, label:  Liver Regeneration & Fibrosis Treatment
Topic: 31, label:  Aβ-induced coagulation in AD
Topic: 32, label:  Genetic Susceptibility & CARD15 Polymorphisms
Topic: 33, label:  Bile-induced liver injury & inflammation management.
Topic: 34, label:  Aortic Valve Replacement & AF Recurrence
Topic: 35, label:  RA Pathogenesis & Biomarkers
Topic: 36, label:  Acute Pancreatitis Treatment & Research
Topic: 37, label:  High-Frequency Ventilation & Right Ventricular Function
Topic: 38, label:  Preterm Neonatal Care & AN Identification.
Topic: 39, label:  Prostate Cancer Prognosis & Androgen Receptor
Topic: 40, label:  H. pylori Eradication & Gastric Health
Topic: 41, label:  Prostate Cancer Diagnosis & PSA Analysis.
Topic: 42, label:  Bone Regeneration & MSCs
Topic: 43, label:  Exercise-induced Sarcopenia Management
Topic: 44, label:  Cochlear Implant Speech Recognition & Noise Benefit
Topic: 45, label:  Sperm Quality & Genetic Defects
Topic: 46, label:  GH secretion, fasting, diagnosis, children, pituitary, label: Fasting-Induced GH Diagnosis.
Topic: 47, label:  Acute Rejection, Allograft, Immunity, Cytokines, Risk Factor.
Topic: 48, label:  Insulin Resistance & NAFLD Diabetes Risk
Topic: 49, label:  Seizure-onset patterns & HFO analysis.
Topic: 50, label:  Angiotensin II effects, endothelial, receptor, leak, cAMP independent, label: Endothelial Leakage & Angiotensin II Receptor.
Topic: 51, label:  Sleep Disturbances & Osteoporosis Risk
Topic: 52, label:  Birth Weight & Milk Intake Effects
Topic: 53, label:  Gene Regulatory Networks & Cis-Regulation
Topic: 54, label:  COPD Management & CPAP Efficacy
Topic: 55, label:  Folate Deficiency & Homocysteine Reduction
Topic: 56, label:  GERD Treatment & Esophageal pH Monitoring
Topic: 57, label:  Alcohol Preference & Aversive Effects
Topic: 58, label:  SLE Activity & Anti-C1q Antibodies
Topic: 59, label:  Glucose-related mortality, hyperglycemia, hypoglycemia, diabetes, cardiac surgery.
Topic: 60, label:  Neuroblastoma Epigenetic Silencing
Topic: 61, label:  Smoking Cessation & Nicotine Dependence
Topic: 62, label:  Periodontal Inflammation & Cardiovascular Risk
Topic: 63, label:  Thrombin-PAR4-Thrombosis Prevention
Topic: 64, label:  Burn Injury & Resuscitation Care
Topic: 65, label:  Kidney Transplantation Outcomes & Donor Selection
Topic: 66, label:  Vitamin D Deficiency & Supplementation Effects
Topic: 67, label:  Malaria Control & Transmission Reduction
Topic: 68, label:  Atherosclerotic Plaque Development & MCP-1 Role
Topic: 69, label:  Colonoscopy Missed Polyps & Risk Factors
Topic: 70, label:  Falls Prevention & Self-Efficacy
Topic: 71, label:  Motor Cortical Adaptations
Topic: 72, label:  Carotenoid Biosynthesis Research
Topic: 73, label:  Obesity-related adipokines & insulin resistance
Topic: 74, label:  CMV Vaccine Efficacy & Liver Fibrosis
Topic: 75, label:  Curcumin Ototoxicity & Immune Modulation
Topic: 76, label:  Glucagon Secretion & GLP-1 Interaction
Topic: 77, label:  Postoperative SSI Management & Vancomycin Use
Topic: 78, label:  Pharmacogenetics, drug metabolism, genetic polymorphisms, clearance, interindividual variability.
Topic: 79, label:  Carotid Revascularization Safety & Outcomes
Topic: 80, label:  Treg imbalance, IL-10, IL-17, Foxp3, disease development. Label: Treg Dysregulation & Autoimmunity.
Topic: 81, label:  PCOS Insulin Resistance & Hyperandrogenism
Topic: 82, label:  Stem Cell Myocardial Repair
Topic: 83, label:  HPV Screening & Cervical Cancer Prevention
Topic: 84, label:  Platelet Storage & Cytokine Levels
Topic: 85, label:  Trauma MRI Diagnosis & Care
Topic: 86, label:  Workplace Learning & Peer Support
Topic: 87, label:  Erectile Dysfunction & Sildenafil Effects
Topic: 88, label:  PET-CT Lung Injury Detection
Topic: 89, label:  Migraine with Aura & Depression Linkage
Topic: 90, label:  Waist Measurement & Obesity Risk
Topic: 91, label:  Drug-seeking behavior & relapse prevention.
Topic: 92, label:  Allopurinol, Endothelial Function, Oxidative Stress Reduction
Topic: 93, label:  HDL-3 Protection & Cardiovascular Risk
Topic: 94, label:  Postoperative Coagulation Management
Topic: 95, label:  MS Fatigue & QoL Improvement
Topic: 96, label:  Hypoxia-targeted therapy & HIF-1α inhibition.
Topic: 97, label:  Air Pollution & Respiratory Health
Topic: 98, label:  Islet Transplantation & Survival Improvement
Topic: 99, label:  Autonomic Dysfunction & Cardiovascular Risk
Topic: 100, label:  Insulin, glucose, diabetes, therapy, effectiveness. Label: Diabetes Insulin Therapy Efficacy.
Topic: 101, label:  Parathyroidectomy Sestamibi Scan Evaluation
Topic: 102, label:  Postural Sway & Pain Rehabilitation
Topic: 103, label:  Cannabinoid Receptors & THC Effects
Topic: 104, label:  Phospholipid Depletion & PPC Protection
Topic: 105, label:  DHEA, Insulin, Diabetes, Muscle, Regulation
Topic: 106, label:  Thyroid Function & TSH Range
Topic: 107, label:  TLR3-inflammation, GrzB-regulation, T-cells, CpG-ODN, regulatory.
Topic: 108, label:  Childhood Trauma & PTSD Onset
Topic: 109, label:  Peritoneal Dialysis Solute Transport & Pyruvate Replacement
Topic: 110, label:  Heat Impact on Exercise & Cold Water Immersion
Topic: 111, label:  Early RA Remission & MRI Progression
Topic: 112, label:  Resveratrol Metabolites & Tumor Regression
Topic: 113, label:  Anastomotic Leakage Prevention & Surgery
Topic: 114, label:  Major Liver Resection Efficacy & Recurrence
Topic: 115, label:  Drug Alert Prioritization & Integration
Topic: 116, label:  Fluid balance & mortality, septic shock, catecholamines, resuscitation, cardiac label: Septic Shock & Cardiac Resuscitation.
Topic: 117, label:  Femoral Screw Fracture Management

### Chain-of-thoughts

In [ ]:
for n in range(1,len(topics)):
  cot_shot_prompt = [{
                      "role": "system",
                      "content": "You're a topic labeller system.\
                                  Given a name, representation and representative document you generate the related label.\
                                  Use the given examples as guides to help you produce better outputs."

                    },
                    {
                      "role": "user",
                      "content": f"name: {topics.loc[n]["Name"]}, representation: {topics.loc[n]["Representation"]}, representative document: {topics.loc[n]["Representative_Docs"]}.\
                                  The label must contain max 5 words, capturing the main representative document objective with respect to representation words.\
                                  The output should be concise and easily interpretable.\
                                  There must be only the label as the ouput, followed by a brief (max 75 words) explanation of the chain of thoughts that brought you to such conclusion.\
                                  Examples:\
                                  example1: representative document:{example1["Representative_Docs"]}, representation: {example1["representation"]}, label: {example1["label"]}.\
                                  example2: representative document:{example2["Representative_Docs"]}, representation: {example2["representation"]}, label: {example2["label"]}.\
                                  example3: representative document:{example3["Representative_Docs"]}, representation: {example3["representation"]}, label: {example3["label"]}.",
                    }
                  ]

  output = pipe(cot_shot_prompt) #(LENTO!)
  #print(output[0]["generated_text"]) #prompt + answer
  print(f"Topic: {n}, label: {output[0]["generated_text"][2]["content"]}\n------------------------------\n") #just the answer
  #labelling_results[4].append(output[0]["generated_text"][2]["content"])

Topic: 1, label:  Label: Breast Cancer Prognostic Markers

The representative documents discuss the association of specific biological markers (IL-6, COX-2, apoptosis) with the prognosis and treatment response in breast cancer patients. These markers are linked to poor prognosis, angiogenesis, lymph node metastasis, and treatment resistance. The label "Breast Cancer Prognostic Markers" succinctly captures the essence of these documents, highlighting the focus on prognostic factors in breast cancer research and management. The choice of words reflects the critical elements of the documents: "Breast Cancer" as the disease context, "Prognostic" indicating the predictive nature of the markers, and "Markers" referring to the biological indicators under study. This label effectively conveys the main objective of the documents, which is to identify and understand prognostic markers in breast cancer for improved patient outcomes.
------------------------------

Topic: 2, label:  Label: Allergic Asthma Airway Inflammation

The representative document discusses the effects of Omalizumab on airway inflammation in patients with severe allergic asthma, highlighting the reduction of IL-5 and ET-1 expression. The representation words such as 'asthma', 'allergic', 'airway', 'ige', 'allergen', 'inflammation', and 'atopic' directly relate to the document's focus on allergic asthma's impact on airway inflammation. The label succinctly captures the essence of the document's objective, which is to understand the role of anti-IgE therapy in managing allergic asthma-related airway inflammation.
------------------------------

Topic: 3, label:  Label: Propofol-Analgesia-Spinal Anesthesia

The representative document discusses the use of propofol in combination with other drugs for effective sedation and analgesia during spinal anesthesia in pediatric burn patients. It highlights the synergistic effect of propofol with ketamine or fentanyl, reducing propofol requirements and intraoperative memory. The label captures the essence of propofol's role in analgesia and spinal anesthesia, focusing on its synergistic effects and benefits in sedation.
------------------------------

Topic: 4, label:  Label: Genetic Variants & Metabolic Syndrome

The document discusses the association between genetic variations at the eNOS locus and metabolic syndrome features, suggesting a genetic susceptibility to insulin resistance, hypertriglyceridemia, and low HDL-cholesterol. The focus on genetic mutations, their impact on metabolic traits, and the implication for disease susceptibility leads to the label "Genetic Variants & Metabolic Syndrome." This concise label encapsulates the core objective of the document, highlighting the genetic aspect and its relation to metabolic conditions.
------------------------------

Topic: 5, label:  Label: Pregnancy Complications in Endometriosis

The representative document discusses the association between endometriosis and adverse pregnancy outcomes, such as increased risks of preterm birth and placenta previa. It emphasizes the need for heightened surveillance of pregnant women with endometriosis. The label "Pregnancy Complications in Endometriosis" succinctly captures the essence of the document, highlighting the main concern of pregnancy-related complications arising from endometriosis. The chain of thought is based on the document's focus on the impact of endometriosis on pregnancy, the specific complications mentioned, and the suggested medical response, which is increased monitoring. This label effectively communicates the critical intersection of endometriosis and pregnancy challenges.
------------------------------

Topic: 6, label:  Label: Lymph Node Metastasis Prognosis

The representative documents discuss the prognostic value of lymph node involvement in cancer patients, particularly in non-small cell lung cancer, gastric cancer, and breast cancer. The focus is on how the number of metastatic lymph nodes affects patient prognosis and treatment decisions, such as the need for adjuvant chemotherapy. The label "Lymph Node Metastasis Prognosis" encapsulates the key elements: lymph nodes, metastasis, and prognosis, highlighting the central theme of predicting patient outcomes based on lymph node status.
------------------------------

Topic: 7, label:  Label: Retinal Complications & Surgery Recovery

The representative document discusses ocular complications following retinal implant surgery, such as cataract, vitreous hemorrhage, and retinal detachment. It also mentions the potential role of dopamine in retinal adaptation and the absence of significant vascular changes post-surgery. The label "Retinal Complications & Surgery Recovery" encapsulates the focus on postoperative retinal health and the recovery process, highlighting the main concerns and findings related to retinal surgery outcomes.
------------------------------

Topic: 8, label:  Label: Intestinal Colitis Management

The representative document discusses the impact of colitis on thymus development, predictive factors for disease relapse in CD and UC, and the anti-colitis effects of ML-7. The label "Intestinal Colitis Management" encapsulates the core focus on managing and understanding colitis, particularly in the intestinal context. It highlights the disease's pathogenesis, predictive aspects, and potential treatments, which are central to the document's objective. The choice of words reflects the medical and research-oriented nature of the content, aiming to succinctly convey the main theme of colitis as a condition requiring careful management and study.
------------------------------

Topic: 9, label:  Label: Cardiac Ischemia Reperfusion Injury Protection

The representative document discusses the protective effects of post-conditioning against cold ischemia-reperfusion injury in rats, highlighting the role of eNOS inhibition. The representation words 'injury', 'cardiac', 'ischemia','reperfusion', 'heart', 'ischemic', 'induced', 'cerebral', 'activation' are all related to cardiac and cerebral injury and recovery processes. The label succinctly captures the essence of the document, which is the protection against injury (specifically cardiac and cerebral) caused by ischemia and reperfusion, mediated by eNOS inhibition. This label is derived from the central theme of injury prevention in the context of cardiac and cerebral ischemia-reperfusion events.
------------------------------

Topic: 10, label:  Label: Cancer Therapeutic Targeting miRNAs

Explanation: The representative documents discuss the role of miR-206, miR-221, and miR-222 in cancer, specifically OSCC and gastric cancer, and their potential as therapeutic targets. The label "Cancer Therapeutic Targeting miRNAs" succinctly captures the essence of these findings, emphasizing the therapeutic potential of miRNAs in cancer treatment. The connection between miRNAs and cancer prognosis or treatment strategy is evident, making it a relevant and concise label for these studies.
------------------------------

Topic: 11, label:  Label: CKD-related Cardiovascular Risk

The representative document discusses the association between Chronic Kidney Disease (CKD) and cardiovascular risk factors such as aortic stiffness, serum vitamin D levels, and arterial stiffness. It highlights how CKD contributes to vascular calcification and atherosclerotic disease severity, independent of classical risk factors. The label "CKD-related Cardiovascular Risk" succinctly captures the essence of the document's focus on the cardiovascular implications of CKD. The choice of words reflects the key elements: CKD (chronic kidney disease), cardiovascular (heart and blood vessel health), and risk (potential for disease progression). This label encapsulates the document's primary concern regarding the heightened cardiovascular risk in CKD patients.
------------------------------

Topic: 12, label:  Label: Pediatric HIV Surgical Management

Explanation: The representative document discusses the under-recognition of HIV infection in children presenting as surgical emergencies, the need for early antiretroviral therapy, and the role of surgeons in identifying and managing HIV-positive children. The label "Pediatric HIV Surgical Management" encapsulates the key aspects of the document: pediatric patients, HIV infection, surgical emergencies, and the need for management strategies. It highlights the intersection of pediatric surgery and HIV care, emphasizing the importance of integrated approaches for these vulnerable patients.
------------------------------

Topic: 13, label:  Label: Schizophrenia Social Cognition Treatment

The representative document discusses the potential benefits of intranasal oxytocin in improving social cognition in individuals with schizophrenia. It highlights the complexity of oxytocin's effects on social cognition and suggests its exploration as a treatment adjunct. The label captures the essence of the document's focus on schizophrenia, social cognition, and potential treatment avenues. The choice of words reflects the disorder (schizophrenia), the cognitive aspect affected (social cognition), and the therapeutic approach being considered (treatment). This concise label encapsulates the document's core objective, which is to explore the role of oxytocin in enhancing social cognitive abilities in schizophrenia patients.
------------------------------

Topic: 14, label:  Label: ACL Tear & Knee Kinematics

The representative document discusses the impact of an MMPH longitudinal tear in an ACL-deficient knee on knee kinematics, particularly anterior-posterior tibial translation. It also mentions the improvement in tibial translation post MMPH repair. The label "ACL Tear & Knee Kinematics" succinctly captures the main focus of the document, which is the relationship between ACL tears and changes in knee movement. The inclusion of "ACL" and "kinematics" directly relates to the representation words, while "Tear" signifies the injury being discussed. This label is concise, easily interpretable, and directly tied to the document's core objective.
------------------------------

Topic: 15, label:  Label: HCV Infection Therapeutics

The document discusses the potential for a novel therapeutic approach in treating HCV infection, particularly highlighting the role of NK cells and cytokines in acute HCV infection and disease pathogenesis. It also touches on the genotype-specific risks of cirrhosis and HCC. The label "HCV Infection Therapeutics" succinctly captures the essence of the document's focus on therapeutic strategies for HCV, considering the biological processes and disease outcomes mentioned.
------------------------------

Topic: 16, label:  Label: Plant TOR Functions & Sulfur Metabolism

The representative document discusses the role of TOR pathway in plant growth, particularly in response to drought stress, and its impact on sulfur metabolism. The document highlights the importance of TOR activity in plant translation and the organ-specific effects of drought on sulfur assimilation. The label "Plant TOR Functions & Sulfur Metabolism" succinctly captures the essence of the document, focusing on the TOR pathway's role in plant growth and its interaction with sulfur metabolism during drought stress. This label reflects the key themes of TOR's regulatory function in plant biology and the metabolic adjustments in response to environmental challenges.
------------------------------

Topic: 17, label:  Label: Dental Implant Bone Level Changes

The document discusses the impact of implant geometry, surface roughness, and placement depth on bone level changes in dental implants. The focus is on the precision of bone level evaluation and the significance of these factors in the esthetic zone. The label "Dental Implant Bone Level Changes" succinctly captures the essence of the document, highlighting the main concern regarding the stability and success of dental implants in relation to bone preservation. This label is derived from the key terms 'implant,' 'bone,' and 'level changes,' which are central to understanding the document's findings and implications for dental implantology.
------------------------------

Topic: 18, label:  Label: LV Dysfunction Prognosis

The representative document discusses the association of left ventricular (LV) longitudinal dysfunction with an increased risk of sudden cardiac death and life-threatening ventricular arrhythmias. It emphasizes the importance of echocardiographic measures, including LV function and right heart variables, in prognostication for patients with myocardial infarction. The label "LV Dysfunction Prognosis" succinctly captures the essence of the document's focus on the prognostic implications of LV dysfunction, as indicated by echocardiographic parameters. This label is derived from the key terms 'left ventricular' (LV), 'dysfunction', and 'prognosis', which collectively summarize the document's main objective of linking LV function to patient outcomes.
------------------------------

Topic: 19, label:  Label: Physician Care Management Quality

The representative document discusses the impact of physicians' relationships with health plans on their experiences with care management practices and policies. It suggests that stronger relationships lead to more positive experiences and agreements on improving care quality. The label "Physician Care Management Quality" encapsulates the focus on physicians' roles in care management and the quality of care derived from their interactions with health plans. This concise label reflects the core objective of the document, which is to highlight the correlation between physician-health plan relationships and the quality of care management.
------------------------------

Topic: 20, label:  Label: Bladder Dysfunction & Urodynamic Study

The document discusses the urodynamic study of bladder function, highlighting the effects of bladder filling, the glycogen content as a history marker, and the impact of aging and infections on voiding function. The representation words such as 'bladder', 'urinary', 'incontinence', 'anal', 'hernia','sphincter', 'detrusor', 'continence', 'prolapse', 'with' are all related to bladder function and its disorders. The label succinctly captures the essence of the document, which is focused on the diagnostic and functional aspects of bladder dysfunction.
------------------------------

Topic: 21, label:  Label: Depression & Cognitive Impairment

The representative document discusses the relationship between neuropsychiatric symptoms, particularly depression and apathy, in patients with Mild Cognitive Impairment (MCI). It highlights how these symptoms can predict the progression to Alzheimer's Disease (AD). The label "Depression & Cognitive Impairment" succinctly captures the essence of the document's focus on the impact of depressive symptoms on cognitive decline and the risk of developing dementia. The connection between depression, cognitive performance, and the progression of MCI to AD is central to the document's findings, making this label an accurate and concise summary.
------------------------------

Topic: 22, label:  Label: Dietary Behavior & Weight Management

The representative document discusses the relationship between eating behaviors, fruit/vegetable intake, and weight change, highlighting the impact of text-message interventions promoting healthy eating strategies. The connection between parents' eating habits and children's food intake also suggests the influence of dietary behavior on weight management. The label succinctly captures the essence of the document's focus on dietary habits and their role in managing weight.
------------------------------

Topic: 23, label:  Label: Notch Signaling in Lung Development

The representative document discusses the role of Notch signaling, particularly Jagged1, in regulating cell fate decisions and differentiation in the respiratory system. It highlights the importance of Notch signaling in lung development and maintaining airway cell balance. The connection between Notch signaling, cell positioning (tip cells), and differentiation processes in the lung tissue is emphasized. This label succinctly captures the essence of the document's focus on Notch signaling's impact on lung biology.
------------------------------

Topic: 24, label:  Label: Renal Tubular Injury Prevention

The representative document discusses the protective effects of SM against renal I/R injury-induced tubular changes, highlighting its role in preventing renal tubular necrosis. The document also mentions the potential of PMX-DHP in protecting against acute kidney injury by inhibiting NF-κB signaling and preventing tubular cell apoptosis. The focus on renal tubular injury and the interventions to prevent it led to the label "Renal Tubular Injury Prevention." This label succinctly captures the essence of the document's objective, which is centered on the prevention of renal tubular damage through specific treatments.
------------------------------

Topic: 25, label:  Label: Heart Failure Prognostic Marker

The representative document discusses the use of NT-proBNP as a marker for heart failure and its association with mortality in patients with acute heart failure. The representation words 'NT-proBNP', 'heart failure','mortality', and'ventricular' directly relate to the document's focus on cardiac health and prognosis. The label succinctly captures the essence of the document's objective, which is to highlight NT-proBNP's role as a prognostic marker in heart failure patients.
------------------------------

Topic: 26, label:  Label: Cartilage Degradation & Chondrocyte Role

The representative document discusses the relationship between chondrocyte apoptosis, cartilage damage, and the onset of osteoarthritis (OA). It highlights the significance of chondrocyte interactions and their role in cartilage matrix organization, which are crucial for understanding OA pathology and developing cartilage repair strategies. The label succinctly captures the essence of the document by focusing on the key elements: cartilage degradation and chondrocyte involvement. This label indicates the document's central theme of exploring the cellular processes contributing to joint cartilage deterioration in OA.
------------------------------

Topic: 27, label:  Label: Statin Endothelial Effects

The representative document discusses the impact of statins on endothelial cells, particularly their role in regulating TM expression and influencing endothelial function. It also touches on the concentration- and cell type-dependent effects of statins on angiogenesis and VEGF synthesis, which are crucial for understanding their role in cardiovascular diseases and cancer. The label "Statin Endothelial Effects" succinctly captures the essence of these findings, focusing on the primary cell type (endothelial) and the mechanism of action (statins) that are central to the document's content. This label highlights the significant relationship between statins and their beneficial effects on endothelial health, which is a key aspect of their therapeutic use.
------------------------------

Topic: 28, label:  Label: MRSA Colonization & Infection Control


### Output visualization

In [ ]:
#[0] -> zero_shot_istruzioni
#[1] -> zero_shot_iterativo
#[2] -> few_shot_istruzioni
#[3] -> few_shot_iterativo
#[4] -> chain_of_thought
df = pd.DataFrame({"zero_shot_istruzioni":labelling_results[0],
                   "zero_shot_iterativo":labelling_results[1],
                   "few_shot_istruzioni":labelling_results[2],
                   "few_shot_iterativo":labelling_results[3]})
                   #"chain_of_thought":labelling_results[4]})


with pd.option_context("display.max_rows", None, "display.max_columns", None, "display.max_colwidth", None):
  display(df)

,zero_shot_istruzioni,zero_shot_iterativo,few_shot_istruzioni,few_shot_iterativo
0,Breast cancer prognosis and treatment response prediction,Breast cancer prognosis markers,Breast Cancer Prognostic Markers,Breast Cancer Prognosis & Treatment
1,Anti-IgE therapy reduces airway inflammation in allergic asthma,Allergic Asthma Airway Ige Treatment,Allergic Asthma Inflammation Reduction,Allergic Asthma Airway Inflammation Omalizumab
2,Propofol-Analgesia-Spinal Anesthesia,Spinal anesthesia analgesia propofol,Anesthetic Pain Management,Spinal Anesthesia & Analgesia Management
3,Genetic susceptibility in metabolic syndrome and FMTC mutations,Gene Mutations Risk Assessment,Genetic Variants & Metabolic Syndrome Risk,Gene Mutations & Metabolic Syndrome Risk
4,Endometriosis impact on pregnancy outcomes and ART pregnancy risks,Endometriosis Pregnancy Outcomes,Pregnancy Endometriosis Complications,Endometriosis & Pregnancy Complications
5,Prognostic Lymph Node Metastasis Chemotherapy Impact,Chemotherapy Prognosis Lymph Node Metastasis,Lymph node involvement & chemotherapy timing,Lymph node involvement & prognosis prediction
6,"Retinal implant effects, ocular complications, visual adaptation, glaucoma risk, retinal recovery",Retinal Implant Complications,Ocular Complications & Retinal Adaptation,Retinal Complications & Surgery Recovery
7,Intestinal mucosal colitis treatment in IBD patients,Intestinal IBD Gut Colitis,Intestinal Colitis Relapse Prediction & Treatment,"Intestinal Colitis, IBD, Gut Health, Mucosal Repair, Anti-Colitis Effect."
8,Cardiac Ischemia Reperfusion Protection,Cardiac Ischemia Reperfusion Protection,Ischemic Heart Reperfusion Protection,Ischemic Heart Protection & Reperfusion
9,miRNA expression prognostic therapeutic cancer,miRNA prognostic cancer therapy,"miRNA expression, cancer therapy, prognostic biomarker, label: miRNA Therapeutic Potential.",miRNA Therapeutics & Cancer Prognosis
10,CKD-related arterial stiffness risk in coronary patients,CKD_coronary_risk_stiffness,CKD-related arterial stiffness,CKD Arterial Stiffness Risk
11,"HIV infection, CD4 impairment, antiretroviral management",HIV Surgical Management,HIV Infection & Surgical Outcomes,HIV Infection & Surgical Outcomes
12,"Schizophrenia, Social Cognition, Genetic Links, Mitochondrial Dysfunction, Oxytocin Treatment",Schizophrenia-related disorders and treatments,Schizophrenia Social Cognition Impacts,Schizophrenia Social Cognition Impacts
13,Knee OA load analysis and ACL repair impacts,Knee ACL Tendon Joint OA,ACL Tear & Knee Kinematics,ACL repair & knee kinematics
14,HCV treatment and NK cell activation,HCV treatment strategy,Hepatitis Viral Infection & NK Cells,HCV Infection & NK Activation
15,"Plant TOR function study, N response regulation, Sulfur metabolism drought impact",Plant TOR Functions,Plant TOR Functions & Drought Response,Plant TOR Functions & Drought Response
16,Implant surface effects on bone stability and complications,Dental implant stability and bone changes,Implant Bone Level Changes,Implant Surface & Bone Level Changes
17,"LV dysfunction, echocardiography prognosis, infarct size assessment",LV myocardial CRT ventricular patients echocardiography,LV Dysfunction & Echocardiography Analysis,LV Dysfunction & Sudden Death Risk
18,Evidence-based care improvement research,Care Meta-Reviews Physician Experience,Care Meta-Analysis Quality Assessment,Care Research & Physician Experience
19,Bladder dysfunction recovery assessment,Bladder Incontinence Analysis,"Bladder Incontinence, Urinary Dysfunction, Sphincter Control, Detrusor Activity, Prolapse Management",Bladder Dysfunction & Urodynamic Study
20,Depression progression prediction in MCI and AD risk,Depressive Ad Recovery Impact,Depression Progression & Stroke Recovery,Depression Progression & Stroke Recovery
21,Weight management through dietary behavior,Dietary behavior impact on weight management,Dietary Intervention & Weight Management,Dietary Intervention & Weight Management
22,Notch signaling in cell fate and differentiation,Notch signaling in cell fate and differentiation,Notch signaling in lung development and cell fate,Notch signaling & lung development
23,"Prevent renal tubular injury, fibrosis, inflammation",Renal Tubular Injury Prevention,Renal Tubular Injury Prevention,Renal Tubular Protection & Injury Prevention.
24,Heart failure prognosis and NT-proBNP monitoring,Heart Failure Prognostic Marker,Heart Failure Prognosis & NT-proBNP,Heart Failure Prognosis & NT-proBNP
25,"Cartilage degradation, chondrocyte apoptosis, matrix organization, OA pathology, cartilage repair strategies.",Chondrocyte Differentiation in Articular Cartilage,Cartilage Degradation & Chondrocyte Role,Cartilage Degradation & Chondrocyte Role
26,Statins' endothelial effects and angiogenesis modulation,Statin effects on endothelial cells,Statin Endothelial Effects,Statin-induced Endothelial Function Improvement
27,MRSA Carrier Prevention and Screening,MRSA Carrier Prevention,MRSA Colonization & Infection Control,MRSA Transmission Prevention
28,"Diet-induced obesity prevention, fatty acid regulation",Insulin-fat-adipose-diet-regulation,Obesity & Dietary Fat Regulation,Obesity Prevention & Dietary Fat Regulation
29,"Liver regeneration, hepatocyte therapy, apoptosis reduction, fibrosis treatment, cell transplantation",Liver regeneration hepatocytes,Liver Regeneration & Fibrosis Treatment,Liver Regeneration & Fibrosis Treatment
30,Aβ prothrombotic mechanism in AD dementia,Aβ prothrombotic AD pathology,Aβ-induced Coagulation in AD,Aβ-induced coagulation in AD
31,RA susceptibility polymorphisms study,HLA-CDR Polymorphism Susceptibility,HLA-CD Polymorphisms RA Susceptibility,Genetic Susceptibility & CARD15 Polymorphisms
32,"Bile-induced liver injury, inflammation, sepsis prevention",Bile-induced liver injury label,Bile-induced liver injury & inflammation,Bile-induced liver injury & inflammation management.
33,"AF ablation outcomes in atrial size, time, recurrence",Aortic Valve Ablation Outcomes,Aortic Valve Ablation Outcomes,Aortic Valve Replacement & AF Recurrence
34,RA synovial inflammation biomarkers IL-29 dysregulation,RA inflammatory synovial arthritis IL-29 TNF mtx joints,Synovial Arthritis Inflammation & IL-29 Dysregulation,RA Pathogenesis & Biomarkers
35,Acute pancreatitis treatment strategies,Pancreatic Acute ERCP,Acute Pancreatitis Treatment & NF-κB Inactivation,Acute Pancreatitis Treatment & Research
36,"High-frequency ventilation improvement, right ventricular function monitoring",High-frequency ventilation mitral valve,Ventilation Peep Valve Mitral High-Frequency,High-Frequency Ventilation & Right Ventricular Function
37,Preterm Neonatal Birth Care & Outcomes,Preterm Neonatal Birth Care,Preterm Neonatal Care & Auditory Screening,Preterm Neonatal Care & AN Identification.
38,"Prostate cancer prognosis, gene biomarkers, therapeutic targets",Prostate Cancer Androgen Prostatic Cells,Prostate Cancer Androgen Influence,Prostate Cancer Prognosis & Androgen Receptor
39,"H. pylori infection, gastric cancer, CagA strains, risk reduction, tolerance development",H. pylori eradication impacts gastric diseases,H. pylori Eradication & Gastric Health,H. pylori Eradication & Gastric Health
40,"Prostate cancer risk prediction, PSA levels, biopsy correlation",Prostate Cancer Diagnosis,Prostate Cancer Risk Assessment,Prostate Cancer Diagnosis & PSA Analysis.
41,"Bone regeneration, MSCs, BMP-2, osteogenesis, tissue engineering",Bone regeneration MSCs BMPs Synthetic substitutes,Osteogenic MSCs BMP Healing Tissue,Bone Regeneration & MSCs
42,"Exercise, Bone Mass, Sarcopenia, Osteoporosis, Muscle Strength",Exercise-related sarcopenia management,Exercise-induced Sarcopenia Management,Exercise-induced Sarcopenia Management
43,Cochlear implant speech recognition improvement,Cochlear Implant Speech Perception,Cochlear Implant Performance & Noise Recognition,Cochlear Implant Speech Recognition & Noise Benefit
44,"Sperm quality, antibodies, fertilization impact",Sperm quality study,Sperm Quality & Genetic Defects,Sperm Quality & Genetic Defects
45,"GH secretion, ghrelin levels, IGF-I treatment, obesity, GHD subjects",GH secretion and ghrelin levels in GHD subjects,GH Secretion & Ghrelin Levels,"GH secretion, fasting, diagnosis, children, pituitary, label: Fasting-Induced GH Diagnosis."
46,"Acute rejection markers, donor cytokines, immunosuppression impact.",Acute rejection allografts,"Acute Rejection, Donor IL-6, Kidney Transplantation","Acute Rejection, Allograft, Immunity, Cytokines, Risk Factor."
47,"NAFLD, insulin resistance, diabetes, diet impact, liver health improvement",NAFLD insulin resistance diabetes coffee diet,Insulin Resistance & NAFLD Diabetes Risk,Insulin Resistance & NAFLD Diabetes Risk
48,"Predictors of AED resistance, seizure patterns, HFO analysis",Seizure-onset patterns and HFO analysis,Seizure Onset Patterns & HFO Analysis,Seizure-onset patterns & HFO analysis.
49,Angiotensin II effects without endothelium mediated by type 2 receptors,Angiotensin II type 2 receptor involvement,"Endothelial Damage, Angiotensin II, Losartan, Receptor, Inhibition, Label: Endothelial Angiotensin II Inhibition","Angiotensin II effects, endothelial, receptor, leak, cAMP independent, label: Endothelial Leakage & Angiotensin II Receptor."
50,"Insomnia, sleep quality, sleep duration, sleep disturbances, obesity association",Insomnia Sleep Quality,"Insomnia, Sleep Quality, Osteoporosis Risk",Sleep Disturbances & Osteoporosis Risk
51,"Pregnancy, breastfeeding, offspring weight, gestational disorders, diabetes risk",Gestational Milk Influence on Offspring Weight,Birth Weight & Breastfeeding Diabetes Risk,Birth Weight & Milk Intake Effects
52,Hox gene evolution and regulatory interactions,ProtoHox cluster origin,Hox Gene Evolution & Regulation,Gene Regulatory Networks & Cis-Regulation
53,COPD management and CPAP effectiveness in emphysema patients,COPD management and CPAP effectiveness,COPD Management & CPAP Therapy,COPD Management & CPAP Efficacy
54,"Folate, Homocysteine, Vitamin B12, Hyperhomocysteinemia, Plasma Study Objectives",Folate-Homocysteine-Vitamin B12-Reduction-Study,Folate Deficiency & Homocysteine Reduction,Folate Deficiency & Homocysteine Reduction
55,"GERD treatment, esophageal pH improvement, PPI reduction",Esophageal pH GERD treatment,Esophageal pH & GERD Management,GERD Treatment & Esophageal pH Monitoring
56,"Alcohol consumption, preference, CTA, adolescent rats, early exposure",Alcohol consumption and preference modeling,Alcohol Preference & CTA Development,Alcohol Preference & Aversive Effects
57,"SLE activity, anti-C1q antibodies, disease activity, nephritis, autoantibodies",SLE autoantibodies activity,SLE Autoantibodies & Activity,SLE Activity & Anti-C1q Antibodies
58,"Hypoglycemia, hyperglycemia, mortality risk, glucose management, cardiac surgery patients",Glucose-related mortality in women postmenopausal HRT and diabetes patients.,Hypoglycemia Mortality Risk,"Glucose-related mortality, hyperglycemia, hypoglycemia, diabetes, cardiac surgery."
59,Epigenetic methylation suppression in neuroblastoma,Methylation Promoter Epigenetics Neuroblastoma,"Methylation, Hypermethylation, Promoter, Epigenetic, Neuroblastoma",Neuroblastoma Epigenetic Silencing
60,Smoking cessation and nicotine dependence prediction,Smoking cessation and nicotine replacement,Smoking Cessation & Nicotine Dependence,Smoking Cessation & Nicotine Dependence
61,Periodontal inflammation cardiovascular linkage study,Periodontal inflammation cardiovascular risk,Periodontal Disease & Inflammation,Periodontal Inflammation & Cardiovascular Risk
62,PAR4 inhibition thrombosis prevention,Platelet PAR4 inhibition,PAR4 Inhibition Thrombosis Prevention,Thrombin-PAR4-Thrombosis Prevention
63,Burn injury resuscitation outcomes and gender disparities in HRQoL,Burn Injury Resuscitation Care,Burn Injury Resuscitation & Care,Burn Injury & Resuscitation Care
64,Kidney Transplant Donor Selection and Outcomes,Kidney Transplant Success Factors,Kidney Transplantation Risk Assessment,Kidney Transplantation Outcomes & Donor Selection
65,Vitamin D supplementation effects on BMI and deficiency in women and men.,Vitamin D deficiency study,Vitamin D Deficiency & Supplementation,Vitamin D Deficiency & Supplementation Effects
66,Integrated malaria control and community management,Malaria control integration,Malaria Control & Transmission Reduction,Malaria Control & Transmission Reduction
67,"Atherosclerosis, MCP-1, Macrophage, Therapeutic Target, MKP-1 Deficiency",Atherosclerotic plaque development,Atherosclerotic Plaque Development & MCP-1 Role,Atherosclerotic Plaque Development & MCP-1 Role
68,Colonoscopy polyp detection and adenoma risk assessment,Colorectal polyp detection,Colonoscopy Missed Polyps & Adenomas,Colonoscopy Missed Polyps & Risk Factors
69,"Fall prevention in older adults, self-efficacy, modifiable risk factors",Falls Prevention in Older Adults,Falls Prevention & Self-Efficacy,Falls Prevention & Self-Efficacy
70,Motor cortical excitability alterations in sensorimotor integration,Motor Cortical Visual Excitability,Motor Cortical Excitability Alteration,Motor Cortical Adaptations
71,Carotenoid biosynthesis diversification research,Carotenoid Biosynthesis Research,Carotenoid Biosynthesis Research,Carotenoid Biosynthesis Research
72,"Adiponectin, insulin resistance, obesity markers",Adiponectin-Insulin-Obesity-Inflammation,Obesity-related adipokines & insulin resistance,Obesity-related adipokines & insulin resistance
73,"CMV vaccine efficacy, liver fibrosis, H5N1 protection",CMV vaccine efficacy and liver fibrosis,CMV Vaccine Efficacy & Liver Fibrosis,CMV Vaccine Efficacy & Liver Fibrosis
74,Curcumin immune modulation and cell apoptosis,Curcumin immune modulation,"Ototoxicity, Curcumin, Hair Cells, IFN, Apoptosis",Curcumin Ototoxicity & Immune Modulation
75,"GLP-1 receptor cardiovascular effects, glucagon secretion regulation",GLP-1 and glucagon regulation in cardiovascular system,Glucagon Secretion & GLP-2 Interaction,Glucagon Secretion & GLP-1 Interaction
76,"Vancomycin SSI prevention, postoperative wound management",Postoperative SSI Vancomycin Reduction,Postoperative SSI Vancomycin Treatment,Postoperative SSI Management & Vancomycin Use
77,CYP Polymorphisms Affect Drug Metabolism and Dosing,CYP Polymorphisms Pharmacokinetics Interaction,CYP Polymorphisms & Drug Metabolism,"Pharmacogenetics, drug metabolism, genetic polymorphisms, clearance, interindividual variability."
78,Carotid revascularization safety in octogenarians and recurrent stenosis treatment,Carotid Revascularization Outcomes,Carotid Revascularization Safety & Outcomes,Carotid Revascularization Safety & Outcomes
79,"Treg cell imbalance, IL-17, IL-10, Foxp3, ICOS signaling","Treg cells, IL-17, Foxp3, antibodies, production","Treg cell imbalance, IL-10, IL-17, Foxp3, antibody production, label: Treg Immune Dysregulation.","Treg imbalance, IL-10, IL-17, Foxp3, disease development. Label: Treg Dysregulation & Autoimmunity."
80,"PCOS, insulin resistance, hyperandrogenism, metabolic levels",PCOS hyperandrogenism insulin levels,PCOS Hyperandrogenism Management,PCOS Insulin Resistance & Hyperandrogenism
81,Stem cell therapy for heart repair and regeneration,Stem cell therapy for heart repair,Cardiac Stem Cell Therapy,Stem Cell Myocardial Repair
82,"HPV screening, cervical cancer prevention, women's health",HPV screening impact on cervical cancer in Pakistani women,HPV Screening & Cervical Cancer Prevention,HPV Screening & Cervical Cancer Prevention
83,"Platelet storage, cytokine levels, prestorage leukoreduction",Platelet Storage PCS Cytokines,Platelet Storage & Cytokine Levels,Platelet Storage & Cytokine Levels
84,"Trauma care improvement, patient outcomes, SOP efficiency",Trauma MRI Patient Care,Trauma Injury MRI Diagnosis,Trauma MRI Diagnosis & Care
85,Peer-based clinical skill learning and assessment,Peer-based Clinical Skills Learning,Workplace Learning & Peer Support,Workplace Learning & Peer Support
86,Sildenafil erectile dysfunction cardiovascular safety,Erectile Dysfunction Sildenafil Study,Erectile Dysfunction & Sildenafil Treatment,Erectile Dysfunction & Sildenafil Effects
87,PET imaging for lung injury diagnosis and metastasis detection,PET-CT for lung injury assessment,Lung Injury & FDG-PET Imaging,PET-CT Lung Injury Detection
88,Migraine with Aura and Bipolarity Association,Migraine Aura Study,Migraine with Aura and Depression Link,Migraine with Aura & Depression Linkage
89,Waist circumference cardiovascular risk assessment,Waist Circumference BMI Risk Assessment,Waist Obesity Risk Assessment,Waist Measurement & Obesity Risk
90,"Heroin-seeking behavior, drug relapse prevention, cholinergic transmission, SSM pharmacological agent, BLA neural circuitry",Drug-seeking behavior and relapse prevention,Drug-seeking behavior & relapse prevention,Drug-seeking behavior & relapse prevention.
91,"Allopurinol reduces vascular oxidative stress, affects PTH secretion",Allopurinol-endothelial function,Allopurinol-Endothelial Function Improvement,"Allopurinol, Endothelial Function, Oxidative Stress Reduction"
92,HDL Cholesterol Protection Against CAAD and RA Cardiovascular Risk,HDL-3 and Cardiovascular Risk,HDL Cholesterol & CAAD Protection,HDL-3 Protection & Cardiovascular Risk
93,"Prevent postoperative bleeding, reduce transfusion need",Postoperative Heparin Graft Bleeding Control,Postoperative Bleeding Prevention & Heparin Use,Postoperative Coagulation Management
94,MS Fatigue Impact on QoL and Treatment Response,MS Fatigue QoL Improvement,MS Fatigue Impact on QoL,MS Fatigue & QoL Improvement
95,HIF-1alpha tumor therapy indication,HIF-1alpha inhibition therapy,Hypoxic Tumor Response & HIF-1α,Hypoxia-targeted therapy & HIF-1α inhibition.
96,Air pollution impact on lung health and cardiovascular risk,Air Pollution Impact on Workers' Health,Air Pollution & Respiratory Health,Air Pollution & Respiratory Health
97,Enhance islet transplantation survival and function,Islet Transplantation Efficacy Improvement,Islet Transplantation Survival & Function,Islet Transplantation & Survival Improvement
98,Autonomic modulation in cardiovascular health and stroke risk,Autonomic Heart HRV Study,Autonomic Heart HRV Dysfunction,Autonomic Dysfunction & Cardiovascular Risk
99,"Insulin resistance, pioglitazone, glucose control, adipose tissue, diabetes management",Insulin-pioglitazone-metformin-effect-diabetes,Insulin Therapy & Metabolic Control,"Insulin, glucose, diabetes, therapy, effectiveness. Label: Diabetes Insulin Therapy Efficacy."
100,Parathyroidectomy with sestamibi imaging,Parathyroidectomy Sestamibi Scan,Hyperparathyroidism Surgery Evaluation,Parathyroidectomy Sestamibi Scan Evaluation
101,Postural sway rehabilitation pain assessment,Postural Sway Rehabilitation Pain,Postural Sway Rehabilitation Pain Management,Postural Sway & Pain Rehabilitation
102,Cannabinoid receptor signaling and therapeutic implications,Cannabinoid receptor signaling,Cannabinoid Receptor Signaling & THC Effects,Cannabinoid Receptors & THC Effects
103,"Phospholipid depletion, alcohol-induced liver injury prevention, SAMe restoration",Phospholipid restoration in alcoholic liver,Phospholipid Depletion & PPC Protection,Phospholipid Depletion & PPC Protection
104,"DHEA, Insulin, Myostatin, Testosterone, Diabetes",DHEA_Myostatin_Insulin_Diabetes_Muscle,Insulin Regulation & Myostatin Expression,"DHEA, Insulin, Diabetes, Muscle, Regulation"
105,"Thyroid hormone levels, TSH impact on health, age-related TSH adjustment",Thyroid Hormone Disorders,Thyroid Hormone Disorders,Thyroid Function & TSH Range
106,"CD8 T cells, GrzB, CpG-ODN, regulatory T cells, cytokine regulation",TLR3-CD8-GrzB-CpG-Regulatory-Skin-Inflammation,"CD8 T cells, GrzB, immune regulation, CpG-ODN, skin inflammation.","TLR3-inflammation, GrzB-regulation, T-cells, CpG-ODN, regulatory."

## Definitions

### Zero-shot

**Prompting basato su istruzioni**

In [ ]:
collection = []

for i in range(0,len(definitions)):
  terms_from_definitions = dict()
  cont = 1
  for definition in definitions.loc[i].dropna():
    #print(definition)
    zero_shot_prompt = [{
                      "role": "system",
                      "content": "Sei un sistema il quale, passata una definizione, restituisce la miglior parola descritta dalla definizione fornita."

                    },
                    {
                      "role": "user",
                      "content": f"definizione: {definition}.\
                                  Nell'output voglio venga prodotto solamente il termine che pensi essere descritto dalla definizione passata in input.\
                                  Tale termine deve essere esattamente una singola parola del dizionario italiano.\
                                  Non deve essere prodotto nulla oltre a quanto richiesto.",
                    }
                  ]
    #print("\n---------------------------------------\n")
    output = pipe(zero_shot_prompt)
    #print(output[0]["generated_text"]) #prompt + answer
    print(f"Definizione: {definition}\nTermine individuato:{output[0]["generated_text"][2]["content"]}\n") #just the answer
    term = output[0]["generated_text"][2]["content"].lower()
    if terms_from_definitions.get(term) == None: terms_from_definitions[term] = [f"P{cont}"]
    else: terms_from_definitions[term].append(f"P{cont}")
    cont+=1
  collection.append(terms_from_definitions)
  print("\n--------------------------PROSSIMO TERMINE--------------------------\n\n")

Definizione: Indumento per la parte inferiore del corpo umano
Termine individuato: Cravatta

Definizione: Indumento per le gambe, diviso per ogni gamba può essere lungo o corto e di diversi tessuti
Termine individuato: Calzoni

Definizione: abito indossato sulle gambe
Termine individuato: Calzoni

Definizione: capo di abbigliamento per le gambe
Termine individuato: Calzoni

Definizione: Indumento indossato nella parte inferiore del corpo, copre le gambe.
Termine individuato: Culotte

Definizione: Indumento per la parte inferiore del corpo che può coprire parzialmente o totalmente le gambe.
Termine individuato: Culotte

Definizione: Capo indossabile che copre la parte inferiore del corpo, in cui ogni gamba è coperta singolarmente
Termine individuato: Gonna

Definizione: indumento indossabile da una persona tipicamente di colore blu e particolarmente resistente
Termine individuato: Jeans

Definizione: Indumento che copre le gambe di una persona
Termine individuato: Calzoni

Definizione: Indumento da indossare dalla vita in giù
Termine individuato: Cravatta

Definizione: Indumento vestibile nella parte bassa del corpo
Termine individuato: Culotte

Definizione: Indumento di diverso materiale che si indossa per coprire le gambe
Termine individuato: Calzoni

Definizione: capo di abbigliamento per le gambe, possono essere di diverso materiale
Termine individuato: Calzoni

Definizione: Indumento per coprire le gambe
Termine individuato: Calzoni

Definizione: vestiario da indossare sulle gambe
Termine individuato: Calze

Definizione: indumento indossabile nella parte inferiore del corpo
Termine individuato: Culotte

Definizione: indumento indossato sulle gambe
Termine individuato: CALZONE

Definizione: ritaglio di stoffa lavorato in maniera tale da risultare una protezione per il basso ventre e le gambe
Termine individuato: Cintura

Definizione: Insieme di pezzi di stoffa cuciti tra loro per fornire calore e copertura alla parte inferiore del corpo umano
Termine individuato: Gonna

Definizione: Capo di abbigliamento per la parte inferiore del corpo
Termine individuato: Cappuccio

Definizione: è un indumento per le gambe
Termine individuato: calzoni

Definizione: Indumento che si indossa nella parte bassa del corpo, che serve a coprire le gambe e la parte del basso ventre
Termine individuato: Calzoni

Definizione: È un indumento che si indossa per la parte inferiore del corpo
Termine individuato: Cappotto

Definizione: indumento per coprire le gambe
Termine individuato: gonna

Definizione: Capo di abbigliamento per le gambe
Termine individuato: Calzoni

Definizione: indumento
Termine individuato: vestito

Definizione: indumento che ricopre le gambe e il bacino
Termine individuato: gonna

Definizione: indumento per coprire le gambe
Termine individuato: gonna

Definizione: indumento che copre le gambe
Termine individuato: gonna

Definizione: Indumento per la parte inferiore del corpo provvisto di due separati canali di tessuto per le gambe
Termine individuato: Jeans

Definizione: Indumento per la parte inferiore del corpo dalla cintura fino alle caviglie.
Termine individuato: Culotte

Definizione: Vestiario per la parte le gambe
Termine individuato: Calze

Definizione: Indumento adibito ad essere indossato nella parte inferiore del corpo
Termine individuato: Cravatta

Definizione: Indumento resistente e popolare
Termine individuato: Gilet

Definizione: abbigliamento fatto di tessuto più o meno sintetico che copre le gambe
Termine individuato: Calzoni

Definizione: indumento che si indossa dalla vita in giù, può essere corto o lungo e realizzato con diversi tipi di tessuto
Termine individuato: Gonna

Definizione: capo di abbigliamento indossabile nella parte inferiore del corpo
Termine individuato: Cravatta

Definizione: capo di abbigliamento per coprire le gambe
Termine individuato: gonna

Definizione: Vestito, abito, maschile o femminile che copre le gambe dalla cintura in giù
Termine individuato: gonna

Definizione: Capo d'abbigliamento indossato sulla parte inferiore del corpo.
Termine individuato: Cravatta


--------------------------PROSSIMO TERMINE--------------------------


Definizione: Strumento scientifico per l'osservazione di micro-organismi
Termine individuato: Microscope

Definizione: Dispositivo ottico o elettronico per ispezionare oggetti molto piccoli e solitamente non visibili ad occhio nudo
Termine individuato: microscopio

Definizione: strumento dotato di lenti che permette di visualizzare entità molto piccole
Termine individuato: microscopio

Definizione: strumento per osservare da vicino cose molto piccole
Termine individuato: microscopio

Definizione: Strumento scientifico utilizzato per ingrandire oggetti
Termine individuato: Microscope

Definizione: Strumento che permette di ingrandire oggetti ed elementi fino a una scala impossibile da raggiungere ad occhio nudo.
Termine individuato: Microscopio

Definizione: dispositivo per vedere oggetti visibili solo nella scale delle cellule
Termine individuato: Microscopio

Definizione: dispositivo utilizzato per l'analisi e la visione di dettagli piccoli invisibili ad occhio nudi in oggetti di varia natura
Termine individuato: microscopio

Definizione: Strumento per osservare elementi non visibili a occhio nudo
Termine individuato: Telescopio

Definizione: Strumento impiegato per facilitare la visualizzazione di oggetti molto piccoli e non direttamente visibili a occhio nudo
Termine individuato: microscopio

Definizione: Strumento utilizzato per ingrandire elementi difficili o impossibili da visualizzare a occhio nudo
Termine individuato: microscopio

Definizione: Strumento di precisione utilizzato per osservare oggetti di piccole dimensioni in campo scientifico
Termine individuato: microscopio

Definizione: strumento scientifico che, usando diverse tecnologie, permette di vedere oggetti invisibili ad occhio nudo
Termine individuato: Radar

Definizione: Strumento utilizzato in ambito scientifico per osservare corpi molto piccoli
Termine individuato: Microscope

Definizione: strumento utile ad osservare entità microscopiche e microrganismi
Termine individuato: Microscopio

Definizione: strumento utilizzato per osservare materia a livello di particelle
Termine individuato: microscopio

Definizione: strumento di laboratorio per aumentare le dimensioni di oggetti/organismi piccolissimi
Termine individuato: Micromacchina

Definizione: strumento scientifico utilizzato per osservare "oggetti" molto piccoli
Termine individuato: microscopio

Definizione: Prodigio della scienza che permette di osservare elementi e/o organismi normalmente non visibili ad occhio nudo
Termine individuato: Telescopio

Definizione: Strumento per osservare oggetti di piccole dimensioni non visibili ad occhio nudo
Termine individuato: Microscoppio

Definizione: Strumento per analizzare nel dettaglio oggetti di piccole dimensioni
Termine individuato: microscopio

Definizione: Strumento scientifico composto da una base su cui appoggiare il materiale da analizzare e un corpo, composto da diverse lenti d'ingrandimento e un cilindro tramite cui è possibile vedere il materiale analizzato.
Termine individuato: Ottica

Definizione: È uno strumento che viene utilizzato come una lente di ingradimento molto potente per vedere cose che non si riescono a vedere con l'occhio umano.
Termine individuato: Microscopio

Definizione: strumento usato in ambito scientifico per l'osservazione di oggetti molto piccoli
Termine individuato: microscopio

Definizione: Strumento scientifico per l'osservazione di elementi dell'ordine di grandezza di 10^-6
Termine individuato: Microscope

Definizione: apparecchio scientifico
Termine individuato: apparecchio

Definizione: strumento dotato di ottiche capace di ingrandire l'elemento posto dietro la lente
Termine individuato: microscopio

Definizione: strumento scientifico per analizzare i dettagli di oggetti
Termine individuato: microscopio

Definizione: strumento tecnologico per vedere cose molto piccole
Termine individuato: microscopio

Definizione: Macchinario dotato di lente atta ad ingrandire un oggetto
Termine individuato: Ottica

Definizione: Strumento utilizzato per osservare e analizzare oggetti e fenomeni altrimenti invisibili a occhio nudo.
Termine individuato: Telescopio

Definizione: Strumento che consente di osservare elementi non visibili all'occhio umano
Termine individuato: Telescopio

Definizione: strumento che ingranisce oggetti piccoli
Termine individuato: ingranaggio

Definizione: strumento scientifico con scopo di ricerca su organismi non visibili all’occhio umano
Termine individuato: microscopio

Definizione: strumento per la visione ingrandita di oggetti a bassi ordini di grandezza
Termine individuato: microscopio

Definizione: strumento scientifico per osservare oggetti non visibili ad occhio nudo
Termine individuato: telescopio

Definizione: un dispositivo scientifico che utilizza lenti per ingrandire gli oggetti
Termine individuato: microscopio

Definizione: strumento generalmente utilizzato a scopi di ricerca che serve a massimizzare la visione di elementi o entità di piccole dimensioni
Termine individuato: microscopio

Definizione: Strumento utilizzato per vedere oggetti di piccole dimansioni
Termine individuato: microscopio


--------------------------PROSSIMO TERMINE--------------------------


Definizione: Situazione potenzialmente rischiosa
Termine individuato: rischio

Definizione: Situazione in cui si teme per la propria o altrui incolumità, le caue pssono essere ambientali o psicologiche.
Termine individuato: pericolo

Definizione: condizione che può causare danni alle persone e oggetti conivolti
Termine individuato: danneggiamento

Definizione: Evento che minaccia la sicurezza di una persona
Termine individuato: minaccia

Definizione: Situazione dove é minacciata la sicurezza di una persona.
Termine individuato: minaccia

Definizione: Situazione in cui è a rischio l’incolumità di qualcuno o qualcosa.
Termine individuato: pericolo

Definizione: Evento in cui ci si la propria vita si sente minacciata
Termine individuato: minaccia

Definizione: situazione che compromette la sicurezza di un soggetto
Termine individuato: compromettere

Definizione: situazione che minaccia la sicurezza di un soggetto
Termine individuato: minaccia

Definizione: Situazione in cui l’incolumità della persona è a rischio
Termine individuato: pericolo

Definizione: Situazione di poca sicurezza
Termine individuato: incertezza

Definizione: Una situazione o un evento che può nuocere fisicamente o psicologicamente una persona
Termine individuato: trauma

Definizione: minaccia alla sicurezza di persone, oggetti o sistemi
Termine individuato: pericolo

Definizione: Percezione umana innescata da un evento che mina la sicurezza del soggetto
Termine individuato: minaccia

Definizione: evento rischioso che può ledere alla incolumità fisica o mentale di una persona
Termine individuato: rischio

Definizione: situazione che può arrecare danno
Termine individuato: danno

Definizione: evento che rappresenta un rischio per l'integrità di un altro evento, oggetto o persona
Termine individuato: rischio

Definizione: rischio, minaccia
Termine individuato: rischio

Definizione: Situazione generica in cui una persona, animale o cosa non vorrebbe ritrovarsi onde evitare una improvvisa riduzione delle proprie aspettative di vita.
Termine individuato: evitamento

Definizione: Situazione o sensazione di minaccia
Termine individuato: minaccia

Definizione: Situazione che attiva un meccanismo di difesa per la tua incolumità
Termine individuato: difesa

Definizione: Percezione di una situazione di manato confort in cui l'individuo si sente sotto attacco ed è pronto alla fuga
Termine individuato: fuga

Definizione: È una situazione spaventosa e ansiosa che può comportare ad avvenimenti molto brutti.
Termine individuato: terrore

Definizione: situazione che mette a rischio l'incolumità di un individuo
Termine individuato: pericolo

Definizione: Situazione o sentimento che provoca insicurezza
Termine individuato: incertezza

Definizione: minaccia
Termine individuato: minaccia

Definizione: situazione o sentimento provato da una persona di insicurezza, instabilità e paura
Termine individuato: paura

Definizione: è in una situazione in cui un individuo teme per la sua incolumità in determinate circostanze
Termine individuato: paura

Definizione: Contesto che mina la sicurezza o l'integrità di qualcosa
Termine individuato: compromettere

Definizione: Situazione in cui la propria o altrui incolumità è a rischio.
Termine individuato: pericolo

Definizione: Situazione in cui l'incolumità fisica o psicologica è minacciata
Termine individuato: minaccia

Definizione: situazione che può provocare sofferenza
Termine individuato: sofferenza

Definizione: situazioni in cui viene messa a rischio la vita di un individuo
Termine individuato: pericolo

Definizione: situazione in cui si rischia di subire una qualche forma di danno
Termine individuato: rischio

Definizione: percezione di una situazione di minaccia
Termine individuato: minaccia

Definizione: situazione di rischio
Termine individuato: rischio

Definizione: situazione in cui si teme di essere esposti a danni fisici o morali
Termine individuato: paura

Definizione: E' una caratteristica che definisce situazioni che possono portare a un danno dell'individuo
Termine individuato: Pericolo


--------------------------PROSSIMO TERMINE--------------------------


Definizione: Strategia di ricerca nello spazio degli stati
Termine individuato: strategia

Definizione: Strategia di ricerca che permette di stimare il costo che separa la soluzione attualmente selezionata dall'obbiettivo da raggiungere. Permette di scegliere la strada più promettente per proseguire la ricerca
Termine individuato: gradient

Definizione: regola che permette di approssimare una soluzione ottima a un problema
Termine individuato: ottimizzazione

Definizione: Funzione che stima la distanza dallo stato attuale allo stato obiettivo.
Termine individuato: Distanza

Definizione: Strategia adottata durante la risoluzione di un problema al fine di raggiungere la soluzione in maniera più rapida ed efficiente.
Termine individuato: Strategia

Definizione: Funzione per approssimare un comportamento
Termine individuato: approssimazione

Definizione: ipotesi assunta nella ricerca scientifica e metodologia adottata
Termine individuato: ipotesi

Definizione: Metodologia di ricerca di fatti o verità
Termine individuato: Ricerca

Definizione: Metedologia per trovare soluzione migliore rispetto al problema dato
Termine individuato: Metodologia

Definizione: Criterio per stimare la bontà di un percorso scelto da un algoritmo
Termine individuato: qualità

Definizione: Una tecnica che può essere utilizzata per ottimizzare, migliorare o semplificare un qualche tipo di problema matematico o algoritmico
Termine individuato: ottimizzazione

Definizione: criterio in base a cui un processo decisionale, spesso un algoritmo, è in grado di scegliere tra possibili alternative quella migliore
Termine individuato: ottimizzazione

Definizione: Misura utilizzata per stimare la bontá di una scelta ai fini di raggiungere un goal
Termine individuato: efficacia

Definizione: regola da utilizzare per semplificare la risoluzione di un problema
Termine individuato: regola

Definizione: linea guida
Termine individuato: linea

Definizione: Regola per aiutare a prendere decisioni
Termine individuato: regola

Definizione: parte della scienza che ha come oggetto la ricerca tramite stima
Termine individuato: stima

Definizione: Regola stipulata in quanto direttrice (e metodo di valutazione) di una ricerca di un risultato dato un problema preso in considerazione.
Termine individuato: direzione

Definizione: Assunzione di fatti nell'ipotesi di lavoro che guidano il processo
Termine individuato: Processo

Definizione: Stima di un costo utile a guidare un processo di decisone
Termine individuato: costo

Definizione: È un criterio che viene utilizzato come stima in dei calcoli.
Termine individuato: stima

Definizione: regola per semplificare e ottimizzare la soluzione di un problema
Termine individuato: regola

Definizione: Approccio di problem solving
Termine individuato: problem solving

Definizione: insieme di strategie
Termine individuato: strategie

Definizione: metrica usata per guidare una strategia
Termine individuato: strategia

Definizione: insieme di strategie da utilizzare come linee guida
Termine individuato: guida

Definizione: Approccio alla ricerca basato sull'evidenza empirica e sull'intuizione
Termine individuato: Evidenziamento

Definizione: Funzione utilizzata per stimare la distanza dallo stato attuale al goal.
Termine individuato: Distanza

Definizione: Criterio utilizzato al fine dell'ottenimento di un determinato obiettivo
Termine individuato: Obiettivo

Definizione: scorciatoia mentale utilizzata per risolvere problemi complessi
Termine individuato: shortcut

Definizione: stima che viene utilizzata per calcolare i costi più ottimali nella ricerca di soluzioni algoritmiche nel campo informatico


Termine individuato: ottimizzazione

Definizione: approssimazione fatta rispetto a un insieme di strategie o un comportamento reale, tipicamente seguita per ottenere una semplificazione
Termine individuato: approssimazione

Definizione: funzione che permette di calcolare un risultato che dovrà poi essere validato
Termine individuato: validazione

Definizione: un insieme di metodi di ricerca che facilitano la scoperta delle cose precedentemente sconosciute
Termine individuato: Ricerca

Definizione: strategia o procedimento per ricercare elementi pratici o teorici per risolvere un problema
Termine individuato: ricerca

Definizione: E' un valore di stima per difetto
Termine individuato: difetto


--------------------------PROSSIMO TERMINE--------------------------

**Output visualization**

In [ ]:
original_terms = ["pantalone","microscopio","pericolo","euristica"]

for index,group in enumerate(collection):
  print(original_terms[index])
  for term in group:
    print(f"{term}: {group[term]}")
  print("\n----------------------------------------------\n")

pantalone
 cravatta: ['P1', 'P10', 'P33', 'P37', 'P40']
 calzoni: ['P2', 'P3', 'P4', 'P9', 'P12', 'P13', 'P14', 'P21', 'P22', 'P25', 'P35']
 culotte: ['P5', 'P6', 'P11', 'P16', 'P31']
 gonna: ['P7', 'P19', 'P24', 'P27', 'P28', 'P29', 'P36', 'P38', 'P39']
 jeans: ['P8', 'P30']
 calze: ['P15', 'P32']
 calzone: ['P17']
 cintura: ['P18']
 cappuccio: ['P20']
 cappotto: ['P23']
 vestito: ['P26']
 gilet: ['P34']

----------------------------------------------

microscopio
 microscope: ['P1', 'P5', 'P14', 'P25']
 microscopio: ['P2', 'P3', 'P4', 'P6', 'P7', 'P8', 'P10', 'P11', 'P12', 'P15', 'P16', 'P18', 'P21', 'P23', 'P24', 'P27', 'P28', 'P29', 'P34', 'P35', 'P37', 'P38', 'P39']
 telescopio: ['P9', 'P19', 'P31', 'P32', 'P36']
 radar: ['P13']
 micromacchina: ['P17']
 microscoppio: ['P20']
 ottica: ['P22', 'P30']
 apparecchio: ['P26']
 ingranaggio: ['P33']

----------------------------------------------

pericolo
 rischio: ['P1', 'P15', 'P17', 'P18', 'P34', 'P36']
 pericolo: ['P2', 'P6', 'P10', 'P13', 'P24', 'P30', 'P33', 'P38']
 danneggiamento: ['P3']
 minaccia: ['P4', 'P5', 'P7', 'P9', 'P14', 'P20', 'P26', 'P31', 'P35']
 compromettere: ['P8', 'P29']
 incertezza: ['P11', 'P25']
 trauma: ['P12']
 danno: ['P16']
 evitamento: ['P19']
 difesa: ['P21']
 fuga: ['P22']
 terrore: ['P23']
 paura: ['P27', 'P28', 'P37']
 sofferenza: ['P32']

----------------------------------------------

euristica
 strategia: ['P1', 'P5', 'P25']
 gradient: ['P2']
 ottimizzazione: ['P3', 'P11', 'P12', 'P31']
 distanza: ['P4', 'P28']
 approssimazione: ['P6', 'P32']
 ipotesi: ['P7']
 ricerca: ['P8', 'P34', 'P35']
 metodologia: ['P9']
 qualità: ['P10']
 efficacia: ['P13']
 regola: ['P14', 'P16', 'P22']
 linea: ['P15']
 stima: ['P17', 'P21']
 direzione: ['P18']
 processo: ['P19']
 costo: ['P20']
 problem solving: ['P23']
 strategie: ['P24']
 guida: ['P26']
 evidenziamento: ['P27']
 obiettivo: ['P29']
 shortcut: ['P30']
 validazione: ['P33']
 difetto: ['P36']

----------------------------------------------

**Prompting iterativo**

In [ ]:
collection = []

for i in range(0,len(definitions)):
  terms_from_definitions = dict()
  cont = 1
  for definition in definitions.loc[i].dropna():
    #print(definition)
    zero_shot_prompt = [{
                      "role": "system",
                      "content": "Sei un sistema il quale, passata una definizione, restituisce esclusivamente il miglior termine descritto dalla definizione fornita seguendo le istruzioni date."

                    },
                    {
                      "role": "user",
                      "content": f"definizione: {definition}.\
                                  Nell'output voglio venga prodotto solamente il termine che pensi essere descritto dalla definizione passata in input.\
                                  Tale termine deve essere esattamente una singola parola del dizionario italiano.\
                                  Non deve essere prodotto nulla oltre al singolo.\
                                  Istruzioni:\
                                  1. A partire dalla definizione risali a 5 termini descritti da essa.\
                                  2. Crea una definizione poco più generale rispetto a quella fornita ed estrai 5 termini a partire da essa.\
                                  3. Crea una definizione poco più specifica rispetto a quella fornita ed estrai 5 termini a partire da essa.\
                                  4. Dall'insieme complessivo di termini ottenuto restituisci il termine che li accomuna semanticamente.\
                                  4. Restituisci esclusivamente il singolo termine individuato. Non voglio che tu restituisca le definizioni o ragionamenti che hai fatto.",
                    }
                  ]
    #print("\n---------------------------------------\n")
    output = pipe(zero_shot_prompt)
    #print(output[0]["generated_text"]) #prompt + answer
    print(f"Definizione: {definition}\nTermine individuato:{output[0]["generated_text"][2]["content"]}\n") #just the answer
    term = output[0]["generated_text"][2]["content"].lower()
    if terms_from_definitions.get(term) == None: terms_from_definitions[term] = [f"P{cont}"]
    else: terms_from_definitions[term].append(f"P{cont}")
    cont+=1
  collection.append(terms_from_definitions)
  print("\n--------------------------PROSSIMO TERMINE--------------------------\n\n")

Definizione: Indumento per la parte inferiore del corpo umano
Termine individuato: Pantaloni

Definizione: Indumento per le gambe, diviso per ogni gamba può essere lungo o corto e di diversi tessuti
Termine individuato: Calzatura

Definizione: abito indossato sulle gambe
Termine individuato: Calzoni

Definizione: capo di abbigliamento per le gambe
Termine individuato: Calzatura

Definizione: Indumento indossato nella parte inferiore del corpo, copre le gambe.
Termine individuato: Calzini

Definizione: Indumento per la parte inferiore del corpo che può coprire parzialmente o totalmente le gambe.
Termine individuato: Calzini

Definizione: Capo indossabile che copre la parte inferiore del corpo, in cui ogni gamba è coperta singolarmente
Termine individuato: Gonna

Definizione: indumento indossabile da una persona tipicamente di colore blu e particolarmente resistente
Termine individuato: Jeans

Definizione: Indumento che copre le gambe di una persona
Termine individuato: Calze

Definizione: Indumento da indossare dalla vita in giù
Termine individuato: Cravatta

Definizione: Indumento vestibile nella parte bassa del corpo
Termine individuato: Calzatura

Definizione: Indumento di diverso materiale che si indossa per coprire le gambe
Termine individuato: Calzature

Definizione: capo di abbigliamento per le gambe, possono essere di diverso materiale
Termine individuato: Calzatura

Definizione: Indumento per coprire le gambe
Termine individuato: Calzature

Definizione: vestiario da indossare sulle gambe
Termine individuato: Calzoni

Definizione: indumento indossabile nella parte inferiore del corpo
Termine individuato: Calzatura

Definizione: indumento indossato sulle gambe
Termine individuato: Calzoni

Definizione: ritaglio di stoffa lavorato in maniera tale da risultare una protezione per il basso ventre e le gambe
Termine individuato: Abbigliamento protettivo

Definizione: Insieme di pezzi di stoffa cuciti tra loro per fornire calore e copertura alla parte inferiore del corpo umano
Termine individuato: Giaccio

Definizione: Capo di abbigliamento per la parte inferiore del corpo
Termine individuato: Jeans

Definizione: è un indumento per le gambe
Termine individuato: Calzatura

Definizione: Indumento che si indossa nella parte bassa del corpo, che serve a coprire le gambe e la parte del basso ventre
Termine individuato: Calzini

Definizione: È un indumento che si indossa per la parte inferiore del corpo
Termine individuato: Pantaloni

Definizione: indumento per coprire le gambe
Termine individuato: Calzatura

Definizione: Capo di abbigliamento per le gambe
Termine individuato: Calzatura

Definizione: indumento
Termine individuato: Robe

Definizione: indumento che ricopre le gambe e il bacino
Termine individuato: Calze

Definizione: indumento per coprire le gambe
Termine individuato: Calzatura

Definizione: indumento che copre le gambe
Termine individuato: Calze

Definizione: Indumento per la parte inferiore del corpo provvisto di due separati canali di tessuto per le gambe
Termine individuato: Calzini

Definizione: Indumento per la parte inferiore del corpo dalla cintura fino alle caviglie.
Termine individuato: Calzoni

Definizione: Vestiario per la parte le gambe
Termine individuato: Calzini

Definizione: Indumento adibito ad essere indossato nella parte inferiore del corpo
Termine individuato: Calzatura

Definizione: Indumento resistente e popolare
Termine individuato: T-shirt

Definizione: abbigliamento fatto di tessuto più o meno sintetico che copre le gambe
Termine individuato: Calzature

Definizione: indumento che si indossa dalla vita in giù, può essere corto o lungo e realizzato con diversi tipi di tessuto
Termine individuato: Vestito

Definizione: capo di abbigliamento indossabile nella parte inferiore del corpo
Termine individuato: Calzatura

Definizione: capo di abbigliamento per coprire le gambe
Termine individuato: Calzatura

Definizione: Vestito, abito, maschile o femminile che copre le gambe dalla cintura in giù
Termine individuato: Calzatura

Definizione: Capo d'abbigliamento indossato sulla parte inferiore del corpo.
Termine individuato: Calzatura


--------------------------PROSSIMO TERMINE--------------------------


Definizione: Strumento scientifico per l'osservazione di micro-organismi
Termine individuato: Microscoppia

Definizione: Dispositivo ottico o elettronico per ispezionare oggetti molto piccoli e solitamente non visibili ad occhio nudo
Termine individuato: Microscoppio

Definizione: strumento dotato di lenti che permette di visualizzare entità molto piccole
Termine individuato: Microscoppia

Definizione: strumento per osservare da vicino cose molto piccole
Termine individuato: Microscoppio

Definizione: Strumento scientifico utilizzato per ingrandire oggetti
Termine individuato: Microscope

Definizione: Strumento che permette di ingrandire oggetti ed elementi fino a una scala impossibile da raggiungere ad occhio nudo.
Termine individuato: Microscopio

Definizione: dispositivo per vedere oggetti visibili solo nella scale delle cellule
Termine individuato: Microscopio

Definizione: dispositivo utilizzato per l'analisi e la visione di dettagli piccoli invisibili ad occhio nudi in oggetti di varia natura
Termine individuato: Microscopio

Definizione: Strumento per osservare elementi non visibili a occhio nudo
Termine individuato: Telescopio

Definizione: Strumento impiegato per facilitare la visualizzazione di oggetti molto piccoli e non direttamente visibili a occhio nudo
Termine individuato: Microscoppio

Definizione: Strumento utilizzato per ingrandire elementi difficili o impossibili da visualizzare a occhio nudo
Termine individuato: Microscopio

Definizione: Strumento di precisione utilizzato per osservare oggetti di piccole dimensioni in campo scientifico
Termine individuato: Ottriometro

Definizione: strumento scientifico che, usando diverse tecnologie, permette di vedere oggetti invisibili ad occhio nudo
Termine individuato: Telescopio

Definizione: Strumento utilizzato in ambito scientifico per osservare corpi molto piccoli
Termine individuato: Ottoscopio

Definizione: strumento utile ad osservare entità microscopiche e microrganismi
Termine individuato: Microscoppia

Definizione: strumento utilizzato per osservare materia a livello di particelle
Termine individuato: Microscopio

Definizione: strumento di laboratorio per aumentare le dimensioni di oggetti/organismi piccolissimi
Termine individuato: Micronica

Definizione: strumento scientifico utilizzato per osservare "oggetti" molto piccoli
Termine individuato: Microscoppio

Definizione: Prodigio della scienza che permette di osservare elementi e/o organismi normalmente non visibili ad occhio nudo
Termine individuato: Telescopio

Definizione: Strumento per osservare oggetti di piccole dimensioni non visibili ad occhio nudo
Termine individuato: Ottrivelo

Definizione: Strumento per analizzare nel dettaglio oggetti di piccole dimensioni
Termine individuato: Microscopio

Definizione: Strumento scientifico composto da una base su cui appoggiare il materiale da analizzare e un corpo, composto da diverse lenti d'ingrandimento e un cilindro tramite cui è possibile vedere il materiale analizzato.
Termine individuato: Microscope

Definizione: È uno strumento che viene utilizzato come una lente di ingradimento molto potente per vedere cose che non si riescono a vedere con l'occhio umano.
Termine individuato: Microscopio

Definizione: strumento usato in ambito scientifico per l'osservazione di oggetti molto piccoli
Termine individuato: Ottoscopio

Definizione: Strumento scientifico per l'osservazione di elementi dell'ordine di grandezza di 10^-6
Termine individuato: Microscoppi

Definizione: apparecchio scientifico
Termine individuato: Sensore

Definizione: strumento dotato di ottiche capace di ingrandire l'elemento posto dietro la lente
Termine individuato: Microscopio

Definizione: strumento scientifico per analizzare i dettagli di oggetti
Termine individuato: Microscopio

Definizione: strumento tecnologico per vedere cose molto piccole
Termine individuato: Microscopio

Definizione: Macchinario dotato di lente atta ad ingrandire un oggetto
Termine individuato: Microscopio

Definizione: Strumento utilizzato per osservare e analizzare oggetti e fenomeni altrimenti invisibili a occhio nudo.
Termine individuato: Telescopio

Definizione: Strumento che consente di osservare elementi non visibili all'occhio umano
Termine individuato: Telescopio

Definizione: strumento che ingranisce oggetti piccoli
Termine individuato: ingranaggio

Definizione: strumento scientifico con scopo di ricerca su organismi non visibili all’occhio umano
Termine individuato: Microscopio

Definizione: strumento per la visione ingrandita di oggetti a bassi ordini di grandezza
Termine individuato: Micrometro

Definizione: strumento scientifico per osservare oggetti non visibili ad occhio nudo
Termine individuato: Telescopio

Definizione: un dispositivo scientifico che utilizza lenti per ingrandire gli oggetti
Termine individuato: Microscoppio

Definizione: strumento generalmente utilizzato a scopi di ricerca che serve a massimizzare la visione di elementi o entità di piccole dimensioni
Termine individuato: Micromicroscopio

Definizione: Strumento utilizzato per vedere oggetti di piccole dimansioni
Termine individuato: Micrometro


--------------------------PROSSIMO TERMINE--------------------------


Definizione: Situazione potenzialmente rischiosa
Termine individuato: Pericolo

Definizione: Situazione in cui si teme per la propria o altrui incolumità, le caue pssono essere ambientali o psicologiche.
Termine individuato: Paura

Definizione: condizione che può causare danni alle persone e oggetti conivolti
Termine individuato: Danno

Definizione: Evento che minaccia la sicurezza di una persona
Termine individuato: Pericolo

Definizione: Situazione dove é minacciata la sicurezza di una persona.
Termine individuato: Pericolo

Definizione: Situazione in cui è a rischio l’incolumità di qualcuno o qualcosa.
Termine individuato: Pericolo

Definizione: Evento in cui ci si la propria vita si sente minacciata
Termine individuato: Stress

Definizione: situazione che compromette la sicurezza di un soggetto
Termine individuato: Pericolo

Definizione: situazione che minaccia la sicurezza di un soggetto
Termine individuato: Pericolo

Definizione: Situazione in cui l’incolumità della persona è a rischio
Termine individuato: Pericolo

Definizione: Situazione di poca sicurezza
Termine individuato: Incertezza

Definizione: Una situazione o un evento che può nuocere fisicamente o psicologicamente una persona
Termine individuato: Stress

Definizione: minaccia alla sicurezza di persone, oggetti o sistemi
Termine individuato: Difesa

Definizione: Percezione umana innescata da un evento che mina la sicurezza del soggetto
Termine individuato: Stress

Definizione: evento rischioso che può ledere alla incolumità fisica o mentale di una persona
Termine individuato: Rischio

Definizione: situazione che può arrecare danno
Termine individuato: Danno

Definizione: evento che rappresenta un rischio per l'integrità di un altro evento, oggetto o persona
Termine individuato: Influenza

Definizione: rischio, minaccia
Termine individuato: Pericolo

Definizione: Situazione generica in cui una persona, animale o cosa non vorrebbe ritrovarsi onde evitare una improvvisa riduzione delle proprie aspettative di vita.
Termine individuato: Ansia

Definizione: Situazione o sensazione di minaccia
Termine individuato: Pericolo

Definizione: Situazione che attiva un meccanismo di difesa per la tua incolumità
Termine individuato: Difesa

Definizione: Percezione di una situazione di manato confort in cui l'individuo si sente sotto attacco ed è pronto alla fuga
Termine individuato: Paura

Definizione: È una situazione spaventosa e ansiosa che può comportare ad avvenimenti molto brutti.
Termine individuato: Paura

Definizione: situazione che mette a rischio l'incolumità di un individuo
Termine individuato: Pericolo

Definizione: Situazione o sentimento che provoca insicurezza
Termine individuato: Ansia

Definizione: minaccia
Termine individuato: Pericolo

Definizione: situazione o sentimento provato da una persona di insicurezza, instabilità e paura
Termine individuato: Paura

Definizione: è in una situazione in cui un individuo teme per la sua incolumità in determinate circostanze
Termine individuato: Paura

Definizione: Contesto che mina la sicurezza o l'integrità di qualcosa
Termine individuato: Comprometto

Definizione: Situazione in cui la propria o altrui incolumità è a rischio.
Termine individuato: Pericolo

Definizione: Situazione in cui l'incolumità fisica o psicologica è minacciata
Termine individuato: Pericolo

Definizione: situazione che può provocare sofferenza
Termine individuato: Dolore

Definizione: situazioni in cui viene messa a rischio la vita di un individuo
Termine individuato: Crisi

Definizione: situazione in cui si rischia di subire una qualche forma di danno
Termine individuato: Pericolo

Definizione: percezione di una situazione di minaccia
Termine individuato: Pericolo

Definizione: situazione di rischio
Termine individuato: Rischio

Definizione: situazione in cui si teme di essere esposti a danni fisici o morali
Termine individuato: Paura

Definizione: E' una caratteristica che definisce situazioni che possono portare a un danno dell'individuo
Termine individuato: Danno


--------------------------PROSSIMO TERMINE--------------------------


Definizione: Strategia di ricerca nello spazio degli stati
Termine individuato: Espansione

1. Generale: La strategia di espansione in vari campi.
Termini: crescita, sviluppo, innovazione, espansione, diversificazione

2. Specifica: Strategia di espansione aziendale.
Termini: acquisizione, partnership, penetrazione di mercato, espansione geografica, diversificazione prodotti

3. Specifica: Strategia di espansione digitale.
Termini: digitalizzazione, marketing online, espansione di piattaforme, integrazione tecnologica, crescita dei social media

4. Termine comune: Espansione

Risposta: Espansione

Definizione: Strategia di ricerca che permette di stimare il costo che separa la soluzione attualmente selezionata dall'obbiettivo da raggiungere. Permette di scegliere la strada più promettente per proseguire la ricerca
Termine individuato: Selezione

Definizione: regola che permette di approssimare una soluzione ottima a un problema
Termine individuato: Ottimizzazione

Definizione: Funzione che stima la distanza dallo stato attuale allo stato obiettivo.
Termine individuato: Guidaggio

1. Termini: Guidaggio, Estimazione, Distanza, Stato, Obiettivo
2. Termini: Guidamento, Stimare, Spazio, Condizione, Punto
3. Termini: Guida, Stimolo, Spazio, Condizione, Punto
4. Termine Comune: Guidaggio

Guidaggio

Definizione: Strategia adottata durante la risoluzione di un problema al fine di raggiungere la soluzione in maniera più rapida ed efficiente.
Termine individuato: Processo decisionale:

1. Dalla definizione originale, identifico i seguenti termini: strategia, risoluzione, problema, rapido, efficiente.
2. Definizione generale: Tecniche utilizzate per affrontare sfide in modo più veloce e migliore. Termini: tecniche, affrontare, sfide, veloce, migliore.
3. Definizione più specifica: Metodo specifico utilizzato per risolvere un problema in modo più rapido e efficiente. Termini: metodo, risolvere, problema, rapido, efficiente.
4. I termini comuni tra tutte le definizioni sono: rapido, efficiente, risolvere, problema, strategia (o metodo).
5. Il termine più generale che accomuna tutti questi concetti è "risolvere".

Risposta: risolvere

Definizione: Funzione per approssimare un comportamento
Termine individuato: Approssimazione

Definizione: ipotesi assunta nella ricerca scientifica e metodologia adottata
Termine individuato: Ricerca

Definizione: Metodologia di ricerca di fatti o verità
Termine individuato: Investigazione

Definizione: Metedologia per trovare soluzione migliore rispetto al problema dato
Termine individuato: ricerca

Definizione: Criterio per stimare la bontà di un percorso scelto da un algoritmo
Termine individuato: Algoritmo

Definizione: Una tecnica che può essere utilizzata per ottimizzare, migliorare o semplificare un qualche tipo di problema matematico o algoritmico
Termine individuato: Rinormalizzazione

Definizione: criterio in base a cui un processo decisionale, spesso un algoritmo, è in grado di scegliere tra possibili alternative quella migliore
Termine individuato: Decisione

Definizione: Misura utilizzata per stimare la bontá di una scelta ai fini di raggiungere un goal
Termine individuato: Benchmarking

Definizione: regola da utilizzare per semplificare la risoluzione di un problema
Termine individuato: Algoritmo

Definizione: linea guida
Termine individuato: Guida

Definizione: Regola per aiutare a prendere decisioni
Termine individuato: Decisione

Definizione: parte della scienza che ha come oggetto la ricerca tramite stima
Termine individuato: Stimazione

Definizione: Regola stipulata in quanto direttrice (e metodo di valutazione) di una ricerca di un risultato dato un problema preso in considerazione.
Termine individuato: Guida
1. Guida: Direttiva per orientare la ricerca di un risultato per un problema specifico.
2. Metodo: Procedura utilizzata per raggiungere un obiettivo o valutare un risultato.
3. Direzione: Linea o percorso seguito per raggiungere un obiettivo.
4. Strumento: Oggetto o metodo utilizzato per raggiungere un risultato o risolvere un problema.
5. Criteri: Standard o parametri utilizzati per valutare o giudicare un risultato.

Termine comune: Guida

La parola "guida" è il termine che accomuna semanticamente tutti gli altri termini, poiché si riferisce a una direzione o metodo utilizzato per raggiungere un obiettivo o valutare un risultato in un contesto di ricerca o problem-solving.

Definizione: Assunzione di fatti nell'ipotesi di lavoro che guidano il processo
Termine individuato: Processo

Definizione: Stima di un costo utile a guidare un processo di decisone
Termine individuato: Progettazione

Definizione: È un criterio che viene utilizzato come stima in dei calcoli.
Termine individuato: Calcolo

Definizione: regola per semplificare e ottimizzare la soluzione di un problema
Termine individuato: Optimizzazione

Definizione: Approccio di problem solving
Termine individuato: Risoluzione

1. Termini dalla definizione originale: Metodo, Soluzione, Risoluzione, Strategia, Tecnica
2. Definizione generale: Modi di affrontare sfide
   Termini: Approccio, Maneuver, Tattica, Procedura, Metodo
3. Definizione specifica: Modi strutturati di risolvere problemi matematici
   Termini: Algoritmo, Formule, Teoremi, Dimostrazioni, Simboli
4. Termine comune: Metodo

Metodo

(Nota: Il termine "Metodo" è comune a tutti i tre livelli di generalità e specificità, rappresentando un approccio o una tecnica sistematica utilizzata per risolvere problemi.)

Definizione: insieme di strategie
Termine individuato: Strategia

Definizione: metrica usata per guidare una strategia
Termine individuato: Strategia

Definizione: insieme di strategie da utilizzare come linee guida
Termine individuato: Guida

Definizione: Approccio alla ricerca basato sull'evidenza empirica e sull'intuizione
Termine individuato: Evidenza

Definizione: Funzione utilizzata per stimare la distanza dallo stato attuale al goal.
Termine individuato: Progressione: funzione di distanza, algoritmo, calcolo, metrica, riferimento

Generale: tecnica, algoritmo, calcolo, misura, riferimento

Specifico: funzione di distanza, algoritmo di ricerca, calcolo di distanza, metrica spaziale, riferimento di goal

Termine comune: riferimento

Risposta: riferimento

Definizione: Criterio utilizzato al fine dell'ottenimento di un determinato obiettivo
Termine individuato: Obiettivo

Definizione: scorciatoia mentale utilizzata per risolvere problemi complessi
Termine individuato: Heuristica


**Output visualization**

In [ ]:
original_terms = ["pantalone","microscopio","pericolo","euristica"]

for index,group in enumerate(collection):
  print(original_terms[index])
  for term in group:
    print(f"{term}: {group[term]}")
  print("\n----------------------------------------------\n")

pantalone
 pantaloni: ['P1', 'P5', 'P11', 'P16', 'P23']
 calzatura: ['P2', 'P3', 'P4', 'P6', 'P9', 'P12', 'P13', 'P14', 'P15', 'P17', 'P21', 'P22', 'P24', 'P25', 'P27', 'P28', 'P29', 'P32', 'P33', 'P35', 'P37', 'P39', 'P40']
 gonna: ['P7']
 jeans: ['P8', 'P20']
 vestito: ['P10', 'P19']
 abbigliamento: ['P18', 'P34']
 abito: ['P26', 'P36']
 calzoni: ['P30', 'P31']
 cappotto: ['P38']

----------------------------------------------

microscopio
 microscoppia: ['P1', 'P4']
 microscopio: ['P2', 'P3', 'P6', 'P7', 'P8', 'P10', 'P14', 'P15', 'P16', 'P21', 'P22', 'P23', 'P24', 'P28', 'P29', 'P30', 'P34']
 microscope: ['P5']
 telescopio: ['P9', 'P19', 'P25', 'P31', 'P32', 'P36']
 occhiature: ['P11']
 microscoppio: ['P12']
 radiografia: ['P13']
 micronutrienti: ['P17']
 ottica: ['P18']
 occhio: ['P20', 'P27', 'P37', 'P39']
 tecnologia: ['P26']
 ingranaggio: ['P33']
 micromicroscopio: ['P35']
 occhiali: ['P38']

----------------------------------------------

pericolo
 rischio: ['P1', 'P17', 'P18', 'P36']
 pericolo: ['P2', 'P4', 'P5', 'P6', 'P9', 'P10', 'P11', 'P15', 'P20', 'P24', 'P26', 'P28', 'P30', 'P31', 'P35']
 danno: ['P3', 'P16', 'P34', 'P38']
 stress: ['P7', 'P12']
 sicurezza: ['P8', 'P13', 'P21']
 ansia: ['P14']
 mortalità: ['P19']
 fuga: ['P22']
 paura: ['P23', 'P37']
 incertezza: ['P25', 'P27']
 corruzione: ['P29']
 dolore: ['P32']
 vita: ['P33']

----------------------------------------------

euristica
 ricerca: ['P1', 'P7', 'P8', 'P9', 'P18', 'P19', 'P34', 'P35']
 selezione: ['P2']
 ottimizzazione: ['P3', 'P22', 'P28']
 guidaggio

1. termini descrittivi: stimatore, distanza, stato, obiettivo, funzione
2. versioni più generali: algoritmo, modello, metodo, strategia, tecnica
3. versioni più specifiche: algoritmo di ottimizzazione, modello di predizione, metodo di distanza, strategia di navigazione, tecnica di estimazione
4. termine più generale: algoritmo

restituisco: algoritmo: ['P4']
 risoluzione: ['P5']
 approssimazione: ['P6']
 algoritmo: ['P10', 'P11']
 decision-making: ['P12', 'P20']
 decisione: ['P13', 'P16']
 regola: ['P14']
 guida: ['P15']
 misurazione: ['P17']
 calcolo: ['P21', 'P33', 'P36']
 risoluzione del problema: ['P23']
 strategia: ['P24', 'P25']
 gestione: ['P26']
 ricerca empirica: ['P27']
 obiettivo: ['P29']
 processo di ragionamento:

1. dalla definizione "scorciatoia mentale utilizzata per risolvere problemi complessi", possiamo identificare il termine "strategia".
2. una versione più generale di "strategia" potrebbe essere "metodo". altri termini che descrivono questo concetto sono "approccio", "procedura", "tecnica" e "pratica".
3. una versione più specifica di "metodo" potrebbe essere "algoritmo". altri termini che descrivono questo concetto sono "formula", "regola", "istruzione" e "sequenza".
4. il termine più generale che accomuna "strategia", "metodo" e "algoritmo" è "tecnica".

risposta: tecnica: ['P30']
 algoritmi: ['P31']
 simplificazione: ['P32']

----------------------------------------------

### Few-shot

**Few-shot examples**

In [ ]:
example1 = {"definition1": "Un insieme di suoni e melodie che ci piace ascoltare per emozionarci o ballare.",
            "definition2": "L'arte di organizzare suoni e silenzi nel tempo, seguendo criteri di armonia, melodia e ritmo",
            "definition3": "Un fenomeno acustico complesso basato sulla manipolazione intenzionale di frequenze d'onda, ampiezze e timbri all'interno di una struttura sintattica definita da intervalli e rapporti matematici.",
            "term": "Musica"}

example2 = {"definition1": "Qualcosa che si sfoglia per leggere storie o imparare cose nuove.",
            "definition2": "Una raccolta di fogli stampati e rilegati insieme, protetti da una copertina, che contiene un testo o delle immagini.",
            "definition3":  "Un supporto informativo strutturato in segnature e destinato alla conservazione e alla trasmissione di contenuti intellettuali attraverso la codifica testuale.",
            "term": "Libro"}

**Prompt basato su istruzioni**

In [ ]:
collection = []

for i in range(0,len(definitions)):
  terms_from_definitions = dict()
  cont = 1
  for definition in definitions.loc[i].dropna():
    #print(definition)
    few_shot_prompt = [{
                      "role": "system",
                      "content": "Sei un sistema il quale, passata una definizione, restituisce la miglior parola descritta dalla definizione fornita.\
                                  Usa come riferimento gli esempi per comprendere come, a partire da definizioni, si possano ottenere i termini associati.\
                                  I termini associati agli esempi non sono per forza quelli che dovrai assegnare alle definizioni che ti verranno passate, ma solo delle spiegazioni su come siano ottenuti a partire dalle loro definizioni."

                    },
                    {
                      "role": "user",
                      "content": f"definizione: {definition}.\
                                  Nell'output voglio venga prodotto solamente il termine che pensi essere descritto dalla definizione passata in input.\
                                  Tale termine deve essere esattamente una singola parola del dizionario italiano.\
                                  Non deve essere prodotto nulla oltre al singolo termine richiesto.\
                                  Le etichette associate agli esempi non sono da intendere come quelle che devi assegnare alle definizioni passate, ma solo come guida.\
                                  Esempi:\
                                  Esempio1: definizione1:{example1["definition1"]}, definizione2: {example1["definition2"]}, definizione3: {example1["definition3"]} termine: {example1["term"]}.\
                                  Esempio2: definizione1:{example2["definition1"]}, definizione2: {example2["definition2"]}, definizione3: {example2["definition3"]} termine: {example2["term"]}.",
                    }
                  ]
    #print("\n---------------------------------------\n")
    output = pipe(few_shot_prompt)
    #print(output[0]["generated_text"]) #prompt + answer
    print(f"Definizione: {definition}\nTermine individuato:{output[0]["generated_text"][2]["content"]}\n") #just the answer
    term = output[0]["generated_text"][2]["content"].lower()
    if terms_from_definitions.get(term) == None: terms_from_definitions[term] = [f"P{cont}"]
    else: terms_from_definitions[term].append(f"P{cont}")
    cont+=1
  collection.append(terms_from_definitions)
  print("\n--------------------------PROSSIMO TERMINE--------------------------\n\n")

Definizione: Indumento per la parte inferiore del corpo umano
Termine individuato: Manica

Definizione: Indumento per le gambe, diviso per ogni gamba può essere lungo o corto e di diversi tessuti
Termine individuato: Indumento per le gambe

Definizione: abito indossato sulle gambe
Termine individuato: Abito

Definizione: capo di abbigliamento per le gambe
Termine individuato: Abito

Definizione: Indumento indossato nella parte inferiore del corpo, copre le gambe.
Termine individuato: Pantaloni

Definizione: Indumento per la parte inferiore del corpo che può coprire parzialmente o totalmente le gambe.
Termine individuato: Abito

Definizione: Capo indossabile che copre la parte inferiore del corpo, in cui ogni gamba è coperta singolarmente
Termine individuato: Scarpa

Definizione: indumento indossabile da una persona tipicamente di colore blu e particolarmente resistente
Termine individuato: Manufatto

Definizione: Indumento che copre le gambe di una persona
Termine individuato: Manica

Definizione: Indumento da indossare dalla vita in giù
Termine individuato: Manzo

Definizione: Indumento vestibile nella parte bassa del corpo
Termine individuato: Manica

Definizione: Indumento di diverso materiale che si indossa per coprire le gambe
Termine individuato: Indumento

Definizione: capo di abbigliamento per le gambe, possono essere di diverso materiale
Termine individuato: Abito

Definizione: Indumento per coprire le gambe
Termine individuato: Indumento per coprire le gambe: Calzatura.

Definizione: vestiario da indossare sulle gambe
Termine individuato: Vestiario da indossare sulle gambe: Calzini.

Definizione: indumento indossabile nella parte inferiore del corpo
Termine individuato: Abito

Definizione: indumento indossato sulle gambe
Termine individuato: Abito

Definizione: ritaglio di stoffa lavorato in maniera tale da risultare una protezione per il basso ventre e le gambe
Termine individuato: Abbbigliamento

Definizione: Insieme di pezzi di stoffa cuciti tra loro per fornire calore e copertura alla parte inferiore del corpo umano
Termine individuato: Abito

Definizione: Capo di abbigliamento per la parte inferiore del corpo
Termine individuato: Abito

Definizione: è un indumento per le gambe
Termine individuato: Indumento per le gambe: Calzatura.

Definizione: Indumento che si indossa nella parte bassa del corpo, che serve a coprire le gambe e la parte del basso ventre
Termine individuato: Abito

Definizione: È un indumento che si indossa per la parte inferiore del corpo
Termine individuato: Manzo

Definizione: indumento per coprire le gambe
Termine individuato: Manzo

Definizione: Capo di abbigliamento per le gambe
Termine individuato: Abito

Definizione: indumento
Termine individuato: Libro

Definizione: indumento che ricopre le gambe e il bacino
Termine individuato: Abito

Definizione: indumento per coprire le gambe
Termine individuato: Indumento per coprire le gambe: Calzatura.

Definizione: indumento che copre le gambe
Termine individuato: Indumento che copre le gambe: Calzatura.

Definizione: Indumento per la parte inferiore del corpo provvisto di due separati canali di tessuto per le gambe
Termine individuato: Abito

Definizione: Indumento per la parte inferiore del corpo dalla cintura fino alle caviglie.
Termine individuato: Indumento

Definizione: Vestiario per la parte le gambe
Termine individuato: Vestiario per la parte le gambe: Calzini.

Definizione: Indumento adibito ad essere indossato nella parte inferiore del corpo
Termine individuato: Abito

Definizione: Indumento resistente e popolare
Termine individuato: Manufatto

Definizione: abbigliamento fatto di tessuto più o meno sintetico che copre le gambe
Termine individuato: Abito

Definizione: indumento che si indossa dalla vita in giù, può essere corto o lungo e realizzato con diversi tipi di tessuto
Termine individuato: Indumento

Definizione: capo di abbigliamento indossabile nella parte inferiore del corpo
Termine individuato: Abito

Definizione: capo di abbigliamento per coprire le gambe
Termine individuato: Abito

Definizione: Vestito, abito, maschile o femminile che copre le gambe dalla cintura in giù
Termine individuato: Abito

Definizione: Capo d'abbigliamento indossato sulla parte inferiore del corpo.
Termine individuato: Abito


--------------------------PROSSIMO TERMINE--------------------------


Definizione: Strumento scientifico per l'osservazione di micro-organismi
Termine individuato: Libro

Definizione: Dispositivo ottico o elettronico per ispezionare oggetti molto piccoli e solitamente non visibili ad occhio nudo
Termine individuato: Manifattura

Definizione: strumento dotato di lenti che permette di visualizzare entità molto piccole
Termine individuato: Libro

Definizione: strumento per osservare da vicino cose molto piccole
Termine individuato: Libro

Definizione: Strumento scientifico utilizzato per ingrandire oggetti
Termine individuato: Libro

Definizione: Strumento che permette di ingrandire oggetti ed elementi fino a una scala impossibile da raggiungere ad occhio nudo.
Termine individuato: Libro

Definizione: dispositivo per vedere oggetti visibili solo nella scale delle cellule
Termine individuato: Libro

Definizione: dispositivo utilizzato per l'analisi e la visione di dettagli piccoli invisibili ad occhio nudi in oggetti di varia natura
Termine individuato: Libro

Definizione: Strumento per osservare elementi non visibili a occhio nudo
Termine individuato: Libro

Definizione: Strumento impiegato per facilitare la visualizzazione di oggetti molto piccoli e non direttamente visibili a occhio nudo
Termine individuato: Libro

Definizione: Strumento utilizzato per ingrandire elementi difficili o impossibili da visualizzare a occhio nudo
Termine individuato: Libro

Definizione: Strumento di precisione utilizzato per osservare oggetti di piccole dimensioni in campo scientifico
Termine individuato: Libro

Definizione: strumento scientifico che, usando diverse tecnologie, permette di vedere oggetti invisibili ad occhio nudo
Termine individuato: Libro

Definizione: Strumento utilizzato in ambito scientifico per osservare corpi molto piccoli
Termine individuato: Libro

Definizione: strumento utile ad osservare entità microscopiche e microrganismi
Termine individuato: Libro

Definizione: strumento utilizzato per osservare materia a livello di particelle
Termine individuato: Manoscritto

Definizione: strumento di laboratorio per aumentare le dimensioni di oggetti/organismi piccolissimi
Termine individuato: Manipolatore di microscopi

Definizione: strumento scientifico utilizzato per osservare "oggetti" molto piccoli
Termine individuato: Libro

Definizione: Prodigio della scienza che permette di osservare elementi e/o organismi normalmente non visibili ad occhio nudo
Termine individuato: Libro

Definizione: Strumento per osservare oggetti di piccole dimensioni non visibili ad occhio nudo
Termine individuato: Libro

Definizione: Strumento per analizzare nel dettaglio oggetti di piccole dimensioni
Termine individuato: Libro

Definizione: Strumento scientifico composto da una base su cui appoggiare il materiale da analizzare e un corpo, composto da diverse lenti d'ingrandimento e un cilindro tramite cui è possibile vedere il materiale analizzato.
Termine individuato: Microscoppio

Definizione: È uno strumento che viene utilizzato come una lente di ingradimento molto potente per vedere cose che non si riescono a vedere con l'occhio umano.
Termine individuato: Libro

Definizione: strumento usato in ambito scientifico per l'osservazione di oggetti molto piccoli
Termine individuato: Manoscritto

Definizione: Strumento scientifico per l'osservazione di elementi dell'ordine di grandezza di 10^-6
Termine individuato: Manoscritto

Definizione: apparecchio scientifico
Termine individuato: Libro

Definizione: strumento dotato di ottiche capace di ingrandire l'elemento posto dietro la lente
Termine individuato: Manufatto ottico

Definizione: strumento scientifico per analizzare i dettagli di oggetti
Termine individuato: Libro

Definizione: strumento tecnologico per vedere cose molto piccole
Termine individuato: Manoscritto

Definizione: Macchinario dotato di lente atta ad ingrandire un oggetto
Termine individuato: Manufatto ottico

Definizione: Strumento utilizzato per osservare e analizzare oggetti e fenomeni altrimenti invisibili a occhio nudo.
Termine individuato: Libro

Definizione: Strumento che consente di osservare elementi non visibili all'occhio umano
Termine individuato: Libro

Definizione: strumento che ingranisce oggetti piccoli
Termine individuato: Libro

Definizione: strumento scientifico con scopo di ricerca su organismi non visibili all’occhio umano
Termine individuato: Manoscritto

Definizione: strumento per la visione ingrandita di oggetti a bassi ordini di grandezza
Termine individuato: Libro

Definizione: strumento scientifico per osservare oggetti non visibili ad occhio nudo
Termine individuato: Libro

Definizione: un dispositivo scientifico che utilizza lenti per ingrandire gli oggetti
Termine individuato: Libro

Definizione: strumento generalmente utilizzato a scopi di ricerca che serve a massimizzare la visione di elementi o entità di piccole dimensioni
Termine individuato: Libro

Definizione: Strumento utilizzato per vedere oggetti di piccole dimansioni
Termine individuato: Libro


--------------------------PROSSIMO TERMINE--------------------------


Definizione: Situazione potenzialmente rischiosa
Termine individuato: Libro

Definizione: Situazione in cui si teme per la propria o altrui incolumità, le caue pssono essere ambientali o psicologiche.
Termine individuato: Libro

Definizione: condizione che può causare danni alle persone e oggetti conivolti
Termine individuato: Libro

Definizione: Evento che minaccia la sicurezza di una persona
Termine individuato: Libro

Definizione: Situazione dove é minacciata la sicurezza di una persona.
Termine individuato: Libro

Definizione: Situazione in cui è a rischio l’incolumità di qualcuno o qualcosa.
Termine individuato: Libro

Definizione: Evento in cui ci si la propria vita si sente minacciata
Termine individuato: Libro

Definizione: situazione che compromette la sicurezza di un soggetto
Termine individuato: Libro

Definizione: situazione che minaccia la sicurezza di un soggetto
Termine individuato: Libro

Definizione: Situazione in cui l’incolumità della persona è a rischio
Termine individuato: Libro

Definizione: Situazione di poca sicurezza
Termine individuato: Libro

Definizione: Una situazione o un evento che può nuocere fisicamente o psicologicamente una persona
Termine individuato: Libro

Definizione: minaccia alla sicurezza di persone, oggetti o sistemi
Termine individuato: Libro

Definizione: Percezione umana innescata da un evento che mina la sicurezza del soggetto
Termine individuato: Libro

Definizione: evento rischioso che può ledere alla incolumità fisica o mentale di una persona
Termine individuato: Libro

Definizione: situazione che può arrecare danno
Termine individuato: Libro

Definizione: evento che rappresenta un rischio per l'integrità di un altro evento, oggetto o persona
Termine individuato: Libro

Definizione: rischio, minaccia
Termine individuato: Libro

Definizione: Situazione generica in cui una persona, animale o cosa non vorrebbe ritrovarsi onde evitare una improvvisa riduzione delle proprie aspettative di vita.
Termine individuato: Libro

Definizione: Situazione o sensazione di minaccia
Termine individuato: Libro

Definizione: Situazione che attiva un meccanismo di difesa per la tua incolumità
Termine individuato: Libro

Definizione: Percezione di una situazione di manato confort in cui l'individuo si sente sotto attacco ed è pronto alla fuga
Termine individuato: Libro

Definizione: È una situazione spaventosa e ansiosa che può comportare ad avvenimenti molto brutti.
Termine individuato: Libro

Definizione: situazione che mette a rischio l'incolumità di un individuo
Termine individuato: Libro

Definizione: Situazione o sentimento che provoca insicurezza
Termine individuato: Libro

Definizione: minaccia
Termine individuato: Libro

Definizione: situazione o sentimento provato da una persona di insicurezza, instabilità e paura
Termine individuato: Libro

Definizione: è in una situazione in cui un individuo teme per la sua incolumità in determinate circostanze
Termine individuato: Libro

Definizione: Contesto che mina la sicurezza o l'integrità di qualcosa
Termine individuato: Libro

Definizione: Situazione in cui la propria o altrui incolumità è a rischio.
Termine individuato: Libro

Definizione: Situazione in cui l'incolumità fisica o psicologica è minacciata
Termine individuato: Libro

Definizione: situazione che può provocare sofferenza
Termine individuato: Libro

Definizione: situazioni in cui viene messa a rischio la vita di un individuo
Termine individuato: Libro

Definizione: situazione in cui si rischia di subire una qualche forma di danno
Termine individuato: Libro

Definizione: percezione di una situazione di minaccia
Termine individuato: Libro

Definizione: situazione di rischio
Termine individuato: Libro

Definizione: situazione in cui si teme di essere esposti a danni fisici o morali
Termine individuato: Libro

Definizione: E' una caratteristica che definisce situazioni che possono portare a un danno dell'individuo
Termine individuato: Libro


--------------------------PROSSIMO TERMINE--------------------------


Definizione: Strategia di ricerca nello spazio degli stati
Termine individuato: Libro

Definizione: Strategia di ricerca che permette di stimare il costo che separa la soluzione attualmente selezionata dall'obbiettivo da raggiungere. Permette di scegliere la strada più promettente per proseguire la ricerca
Termine individuato: Libro

Definizione: regola che permette di approssimare una soluzione ottima a un problema
Termine individuato: Libro

Definizione: Funzione che stima la distanza dallo stato attuale allo stato obiettivo.
Termine individuato: Libro

Definizione: Strategia adottata durante la risoluzione di un problema al fine di raggiungere la soluzione in maniera più rapida ed efficiente.
Termine individuato: Libro

Definizione: Funzione per approssimare un comportamento
Termine individuato: Libro

Definizione: ipotesi assunta nella ricerca scientifica e metodologia adottata
Termine individuato: Libro

Definizione: Metodologia di ricerca di fatti o verità
Termine individuato: Libro

Definizione: Metedologia per trovare soluzione migliore rispetto al problema dato
Termine individuato: Libro

Definizione: Criterio per stimare la bontà di un percorso scelto da un algoritmo
Termine individuato: Libro

Definizione: Una tecnica che può essere utilizzata per ottimizzare, migliorare o semplificare un qualche tipo di problema matematico o algoritmico
Termine individuato: Libro

Definizione: criterio in base a cui un processo decisionale, spesso un algoritmo, è in grado di scegliere tra possibili alternative quella migliore
Termine individuato: Libro

Definizione: Misura utilizzata per stimare la bontá di una scelta ai fini di raggiungere un goal
Termine individuato: Libro

Definizione: regola da utilizzare per semplificare la risoluzione di un problema
Termine individuato: Libro

Definizione: linea guida
Termine individuato: Libro

Definizione: Regola per aiutare a prendere decisioni
Termine individuato: Libro

Definizione: parte della scienza che ha come oggetto la ricerca tramite stima
Termine individuato: Libro

Definizione: Regola stipulata in quanto direttrice (e metodo di valutazione) di una ricerca di un risultato dato un problema preso in considerazione.
Termine individuato: Libro

Definizione: Assunzione di fatti nell'ipotesi di lavoro che guidano il processo
Termine individuato: Libro

Definizione: Stima di un costo utile a guidare un processo di decisone
Termine individuato: Libro

Definizione: È un criterio che viene utilizzato come stima in dei calcoli.
Termine individuato: Libro

Definizione: regola per semplificare e ottimizzare la soluzione di un problema
Termine individuato: Libro

Definizione: Approccio di problem solving
Termine individuato: Libro

Definizione: insieme di strategie
Termine individuato: Libro

Definizione: metrica usata per guidare una strategia
Termine individuato: Libro

Definizione: insieme di strategie da utilizzare come linee guida
Termine individuato: Libro

Definizione: Approccio alla ricerca basato sull'evidenza empirica e sull'intuizione
Termine individuato: Libro

Definizione: Funzione utilizzata per stimare la distanza dallo stato attuale al goal.
Termine individuato: Libro

Definizione: Criterio utilizzato al fine dell'ottenimento di un determinato obiettivo
Termine individuato: Libro

Definizione: scorciatoia mentale utilizzata per risolvere problemi complessi
Termine individuato: Libro

Definizione: stima che viene utilizzata per calcolare i costi più ottimali nella ricerca di soluzioni algoritmiche nel campo informatico


Termine individuato: Libro

Definizione: approssimazione fatta rispetto a un insieme di strategie o un comportamento reale, tipicamente seguita per ottenere una semplificazione
Termine individuato: Libro

Definizione: funzione che permette di calcolare un risultato che dovrà poi essere validato
Termine individuato: Libro

Definizione: un insieme di metodi di ricerca che facilitano la scoperta delle cose precedentemente sconosciute
Termine individuato: Libro

Definizione: strategia o procedimento per ricercare elementi pratici o teorici per risolvere un problema
Termine individuato: Libro

Definizione: E' un valore di stima per difetto
Termine individuato: Musica


--------------------------PROSSIMO TERMINE--------------------------

**Output visualization**

In [ ]:
original_terms = ["pantalone","microscopio","pericolo","euristica"]

for index,group in enumerate(collection):
  print(original_terms[index])
  for term in group:
    print(f"{term}: {group[term]}")
  print("\n----------------------------------------------\n")

pantalone
 manica: ['P1', 'P9', 'P11']
 indumento per le gambe: ['P2']
 abito: ['P3', 'P4', 'P6', 'P13', 'P16', 'P17', 'P19', 'P20', 'P22', 'P25', 'P27', 'P30', 'P33', 'P35', 'P37', 'P38', 'P39', 'P40']
 pantaloni: ['P5']
 scarpa: ['P7']
 manufatto: ['P8', 'P34']
 manzo: ['P10', 'P23', 'P24']
 indumento: ['P12', 'P31', 'P36']
 indumento per coprire le gambe: calzatura.: ['P14', 'P28']
 vestiario da indossare sulle gambe: calzini.: ['P15']
 abbbigliamento: ['P18']
 indumento per le gambe: calzatura.: ['P21']
 libro: ['P26']
 indumento che copre le gambe: calzatura.: ['P29']
 vestiario per la parte le gambe: calzini.: ['P32']

----------------------------------------------

microscopio
 libro: ['P1', 'P3', 'P4', 'P5', 'P6', 'P7', 'P8', 'P9', 'P10', 'P11', 'P12', 'P13', 'P14', 'P15', 'P18', 'P19', 'P20', 'P21', 'P23', 'P26', 'P28', 'P31', 'P32', 'P33', 'P35', 'P36', 'P37', 'P38', 'P39']
 manifattura: ['P2']
 manoscritto: ['P16', 'P24', 'P25', 'P29', 'P34']
 manipolatore di microscopi: ['P17']
 microscoppio: ['P22']
 manufatto ottico: ['P27', 'P30']

----------------------------------------------

pericolo
 libro: ['P1', 'P2', 'P3', 'P4', 'P5', 'P6', 'P7', 'P8', 'P9', 'P10', 'P11', 'P12', 'P13', 'P14', 'P15', 'P16', 'P17', 'P18', 'P19', 'P20', 'P21', 'P22', 'P23', 'P24', 'P25', 'P26', 'P27', 'P28', 'P29', 'P30', 'P31', 'P32', 'P33', 'P34', 'P35', 'P36', 'P37', 'P38']

----------------------------------------------

euristica
 libro: ['P1', 'P2', 'P3', 'P4', 'P5', 'P6', 'P7', 'P8', 'P9', 'P10', 'P11', 'P12', 'P13', 'P14', 'P15', 'P16', 'P17', 'P18', 'P19', 'P20', 'P21', 'P22', 'P23', 'P24', 'P25', 'P26', 'P27', 'P28', 'P29', 'P30', 'P31', 'P32', 'P33', 'P34', 'P35']
 musica: ['P36']

----------------------------------------------

**Prompt iterativo**

In [ ]:
collection = []

for i in range(0,len(definitions)):
  terms_from_definitions = dict()
  cont = 1
  for definition in definitions.loc[i].dropna():
    #print(definition)
    few_shot_prompt = [{
                      "role": "system",
                      "content": "Sei un sistema il quale, passata una definizione, restituisce esclusivamente il miglior termine descritto dalla definizione fornita seguendo le istruzioni date.\
                                  Usa come riferimento gli esempi per comprendere come ottenere il termine associato passate definizioni.\
                                  I termini associati agli esempi non sono per forza quelli che dovrai assegnare alle definizioni che ti verranno passate, ma solo delle spiegazioni su come siano ottenuti a partire dalle loro definizioni."

                    },
                    {
                      "role": "user",
                      "content": f"definizione: {definition}.\
                                  Nell'output voglio venga prodotto solamente il termine che pensi essere descritto dalla definizione passata in input.\
                                  Tale termine deve essere esattamente una singola parola del dizionario italiano.\
                                  Non deve essere prodotto nulla oltre al singolo termine richiesto.\
                                  Le etichette associate agli esempi non sono da intendere come quelle che devi assegnare alle definizioni passate, ma solo come guida.\
                                  Istruzioni:\
                                  1. A partire dalla definizione risali a 5 termini descritti da essa.\
                                  2. Crea una definizione poco più generale rispetto a quella fornita ed estrai 5 termini a partire da essa.\
                                  3. Crea una definizione poco più specifica rispetto a quella fornita ed estrai 5 termini a partire da essa.\
                                  4. Dall'insieme complessivo di termini ottenuto restituisci il termine che li accomuna semanticamente.\
                                  5. Restituisci esclusivamente il singolo termine individuato. Non voglio che tu restituisca le definizioni o ragionamenti che hai fatto.\
                                  Esempi:\
                                  Esempio1: definizione1:{example1["definition1"]}, definizione2: {example1["definition2"]}, definizione3: {example1["definition3"]} termine: {example1["term"]}.\
                                  Esempio2: definizione1:{example2["definition1"]}, definizione2: {example2["definition2"]}, definizione3: {example2["definition3"]} termine: {example2["term"]}.",
                    }
                  ]
    #print("\n---------------------------------------\n")
    output = pipe(few_shot_prompt)
    #print(output[0]["generated_text"]) #prompt + answer
    print(f"Definizione: {definition}\nTermine individuato:{output[0]["generated_text"][2]["content"]}\n") #just the answer
    term = output[0]["generated_text"][2]["content"].lower()
    if terms_from_definitions.get(term) == None: terms_from_definitions[term] = [f"P{cont}"]
    else: terms_from_definitions[term].append(f"P{cont}")
    cont+=1
  collection.append(terms_from_definitions)
  print("\n--------------------------PROSSIMO TERMINE--------------------------\n\n")

Definizione: Indumento per la parte inferiore del corpo umano
Termine individuato: Libro

Definizione: Indumento per le gambe, diviso per ogni gamba può essere lungo o corto e di diversi tessuti
Termine individuato: Manzo

Definizione: abito indossato sulle gambe
Termine individuato: Libro.

Definizione: capo di abbigliamento per le gambe
Termine individuato: Manoscritto.

Definizione: Indumento indossato nella parte inferiore del corpo, copre le gambe.
Termine individuato: Manzo

Definizione: Indumento per la parte inferiore del corpo che può coprire parzialmente o totalmente le gambe.
Termine individuato: Manzo

Definizione: Capo indossabile che copre la parte inferiore del corpo, in cui ogni gamba è coperta singolarmente
Termine individuato: Manoscritto.

Definizione: indumento indossabile da una persona tipicamente di colore blu e particolarmente resistente
Termine individuato: Manufatto.

Definizione: Indumento che copre le gambe di una persona
Termine individuato: Manoscritto.

Definizione: Indumento da indossare dalla vita in giù
Termine individuato: Manoscritto.

Definizione: Indumento vestibile nella parte bassa del corpo
Termine individuato: Manoscritto.

Definizione: Indumento di diverso materiale che si indossa per coprire le gambe
Termine individuato: Manzo

Definizione: capo di abbigliamento per le gambe, possono essere di diverso materiale
Termine individuato: Manzo

Definizione: Indumento per coprire le gambe
Termine individuato: Manoscritto.

Definizione: vestiario da indossare sulle gambe
Termine individuato: Manipolazione delle onde sonore.

Definizione: indumento indossabile nella parte inferiore del corpo
Termine individuato: Manzo.

Definizione: indumento indossato sulle gambe
Termine individuato: Manipolazione delle onde sonore.

Definizione: ritaglio di stoffa lavorato in maniera tale da risultare una protezione per il basso ventre e le gambe
Termine individuato: Abbigliamento.

Definizione: Insieme di pezzi di stoffa cuciti tra loro per fornire calore e copertura alla parte inferiore del corpo umano
Termine individuato: Manipolazione di frequenze d'onda, ampiezze e timbri.

Definizione: Capo di abbigliamento per la parte inferiore del corpo
Termine individuato: Libro.

Definizione: è un indumento per le gambe
Termine individuato: Libro

Definizione: Indumento che si indossa nella parte bassa del corpo, che serve a coprire le gambe e la parte del basso ventre
Termine individuato: Manoscritto.

Definizione: È un indumento che si indossa per la parte inferiore del corpo
Termine individuato: Manzo.

Definizione: indumento per coprire le gambe
Termine individuato: Libro.

Definizione: Capo di abbigliamento per le gambe
Termine individuato: Libro.

Definizione: indumento
Termine individuato: Libro.

Definizione: indumento che ricopre le gambe e il bacino
Termine individuato: Manoscritto.

Definizione: indumento per coprire le gambe
Termine individuato: Manipolazione delle onde sonore.

Definizione: indumento che copre le gambe
Termine individuato: Manipolazione delle onde sonore.

Definizione: Indumento per la parte inferiore del corpo provvisto di due separati canali di tessuto per le gambe
Termine individuato: Manica

1. definizione generale: Una parte di un indumento che copre una parte del corpo., definizione2: Struttura di supporto per il tessuto in un capo di abbigliamento., definizione3: Elemento di un indumento che si estende dalla parte superiore alla parte inferiore., definizione4: Sezione di un indumento progettata per proteggere o coprire una parte del corpo., definizione5: Elemento di un indumento che si estende dalla spalla alla gamba.

2. definizione più specifica: Una sezione di un indumento che copre le gambe., definizione2: Struttura di supporto specifica per le gambe in un indumento., definizione3: Elemento di un indumento che si estende dalla parte superiore alla parte inferiore, specificamente le gambe., definizione4: Sezione di un indumento progettata per coprire le gambe., definizione5: Elemento di un indumento con due canali di tessuto per le gambe.

3. termine: Manica

Il termine "manica" è quello che accomuna semanticamente tutti i termini derivati dalle definizioni, poiché si riferisce specificamente alla parte di un indumento che copre le gam

Definizione: Indumento per la parte inferiore del corpo dalla cintura fino alle caviglie.
Termine individuato: Manipolazione.

Definizione: Vestiario per la parte le gambe
Termine individuato: Manipolazione delle gambe.

Definizione: Indumento adibito ad essere indossato nella parte inferiore del corpo
Termine individuato: Manzo

Definizione: Indumento resistente e popolare
Termine individuato: Manufatto.

Definizione: abbigliamento fatto di tessuto più o meno sintetico che copre le gambe
Termine individuato: Manzo

Definizione: indumento che si indossa dalla vita in giù, può essere corto o lungo e realizzato con diversi tipi di tessuto
Termine individuato: Manoscritto.

Definizione: capo di abbigliamento indossabile nella parte inferiore del corpo
Termine individuato: Manzo.

Definizione: capo di abbigliamento per coprire le gambe
Termine individuato: Manoscritto.

Definizione: Vestito, abito, maschile o femminile che copre le gambe dalla cintura in giù
Termine individuato: Manzo

Definizione: Capo d'abbigliamento indossato sulla parte inferiore del corpo.
Termine individuato: Manzo


--------------------------PROSSIMO TERMINE--------------------------


Definizione: Strumento scientifico per l'osservazione di micro-organismi
Termine individuato: Manuscritto.

Definizione: Dispositivo ottico o elettronico per ispezionare oggetti molto piccoli e solitamente non visibili ad occhio nudo
Termine individuato: Manoscritto.

Definizione: strumento dotato di lenti che permette di visualizzare entità molto piccole
Termine individuato: Manoscritto.

Definizione: strumento per osservare da vicino cose molto piccole
Termine individuato: Libro.

Definizione: Strumento scientifico utilizzato per ingrandire oggetti
Termine individuato: Libro.

Definizione: Strumento che permette di ingrandire oggetti ed elementi fino a una scala impossibile da raggiungere ad occhio nudo.
Termine individuato: Manifattura.

Definizione: dispositivo per vedere oggetti visibili solo nella scale delle cellule
Termine individuato: Manoscritto.

Definizione: dispositivo utilizzato per l'analisi e la visione di dettagli piccoli invisibili ad occhio nudi in oggetti di varia natura
Termine individuato: Manoscritto.

Definizione: Strumento per osservare elementi non visibili a occhio nudo
Termine individuato: Libro.

Definizione: Strumento impiegato per facilitare la visualizzazione di oggetti molto piccoli e non direttamente visibili a occhio nudo
Termine individuato: Manoscritto.

Definizione: Strumento utilizzato per ingrandire elementi difficili o impossibili da visualizzare a occhio nudo
Termine individuato: Libro.

Definizione: Strumento di precisione utilizzato per osservare oggetti di piccole dimensioni in campo scientifico
Termine individuato: Libro.

Definizione: strumento scientifico che, usando diverse tecnologie, permette di vedere oggetti invisibili ad occhio nudo
Termine individuato: Manoscritto.

Definizione: Strumento utilizzato in ambito scientifico per osservare corpi molto piccoli
Termine individuato: Manoscritto.

Definizione: strumento utile ad osservare entità microscopiche e microrganismi
Termine individuato: Manoscritto.

Definizione: strumento utilizzato per osservare materia a livello di particelle
Termine individuato: Manuscrito.

Definizione: strumento di laboratorio per aumentare le dimensioni di oggetti/organismi piccolissimi
Termine individuato: Manipolatore microscopico.

Definizione: strumento scientifico utilizzato per osservare "oggetti" molto piccoli
Termine individuato: Libro.

Definizione: Prodigio della scienza che permette di osservare elementi e/o organismi normalmente non visibili ad occhio nudo
Termine individuato: Manoscritto.

Definizione: Strumento per osservare oggetti di piccole dimensioni non visibili ad occhio nudo
Termine individuato: Libro.

Definizione: Strumento per analizzare nel dettaglio oggetti di piccole dimensioni
Termine individuato: Manoscritto.

Definizione: Strumento scientifico composto da una base su cui appoggiare il materiale da analizzare e un corpo, composto da diverse lenti d'ingrandimento e un cilindro tramite cui è possibile vedere il materiale analizzato.
Termine individuato: Manoscritto.

Definizione: È uno strumento che viene utilizzato come una lente di ingradimento molto potente per vedere cose che non si riescono a vedere con l'occhio umano.
Termine individuato: Libro.

Definizione: strumento usato in ambito scientifico per l'osservazione di oggetti molto piccoli
Termine individuato: Manoscritto.

Definizione: Strumento scientifico per l'osservazione di elementi dell'ordine di grandezza di 10^-6
Termine individuato: Manoscritto.

Definizione: apparecchio scientifico
Termine individuato: Libro.

Definizione: strumento dotato di ottiche capace di ingrandire l'elemento posto dietro la lente
Termine individuato: Manoscritto.

Definizione: strumento scientifico per analizzare i dettagli di oggetti
Termine individuato: Libro.

Definizione: strumento tecnologico per vedere cose molto piccole
Termine individuato: Manoscritto.

Definizione: Macchinario dotato di lente atta ad ingrandire un oggetto
Termine individuato: Manufatto ottico

1. Definizione generale: Un oggetto o dispositivo realizzato con materiali e tecnologie specifiche.
   Termini: Manufatto, Oggetto, Dispositivo, Realizzato, Materiali

2. Definizione più specifica: Un dispositivo realizzato con lenti per ingrandire oggetti.
   Termini: Dispositivo, Realizzato, Lenti, Ingrandire, Oggetti

3. Definizione ancora più specifica: Un macchinario dotato di lenti per ingrandire un oggetto.
   Termini: Macchinario, Lenti, Ingrandire, Oggetto, Dotato

Ingredienti: Macchinario, Lenti, Ingrandire, Oggetto, Dotato

Il termine che li accomuna semanticamente: Macchinario

Termine: Macchinario


Definizione: Strumento utilizzato per osservare e analizzare oggetti e fenomeni altrimenti invisibili a occhio nudo.
Termine individuato: Libro

Definizione: Strumento che consente di osservare elementi non visibili all'occhio umano
Termine individuato: Libro.

Definizione: strumento che ingranisce oggetti piccoli
Termine individuato: Manipolatore

Definizione: strumento scientifico con scopo di ricerca su organismi non visibili all’occhio umano
Termine individuato: Manoscritto.

Definizione: strumento per la visione ingrandita di oggetti a bassi ordini di grandezza
Termine individuato: Manoscritto.

Definizione: strumento scientifico per osservare oggetti non visibili ad occhio nudo
Termine individuato: Manoscritto.

Definizione: un dispositivo scientifico che utilizza lenti per ingrandire gli oggetti
Termine individuato: Manoscritto.

Definizione: strumento generalmente utilizzato a scopi di ricerca che serve a massimizzare la visione di elementi o entità di piccole dimensioni
Termine individuato: Manoscritto.

Definizione: Strumento utilizzato per vedere oggetti di piccole dimansioni
Termine individuato: Libro.


--------------------------PROSSIMO TERMINE--------------------------


Definizione: Situazione potenzialmente rischiosa
Termine individuato: Libro.

Definizione: Situazione in cui si teme per la propria o altrui incolumità, le caue pssono essere ambientali o psicologiche.
Termine individuato: Storia.

Definizione: condizione che può causare danni alle persone e oggetti conivolti
Termine individuato: Libro.

Definizione: Evento che minaccia la sicurezza di una persona
Termine individuato: Libro

Definizione: Situazione dove é minacciata la sicurezza di una persona.
Termine individuato: Libro

Definizione: Situazione in cui è a rischio l’incolumità di qualcuno o qualcosa.
Termine individuato: Libro.

Definizione: Evento in cui ci si la propria vita si sente minacciata
Termine individuato: Libro.

Definizione: situazione che compromette la sicurezza di un soggetto
Termine individuato: Libro.

Definizione: situazione che minaccia la sicurezza di un soggetto
Termine individuato: Libro.

Definizione: Situazione in cui l’incolumità della persona è a rischio
Termine individuato: Libro.

Definizione: Situazione di poca sicurezza
Termine individuato: Libro.

Definizione: Una situazione o un evento che può nuocere fisicamente o psicologicamente una persona
Termine individuato: Libro.

Definizione: minaccia alla sicurezza di persone, oggetti o sistemi
Termine individuato: Manoscritto.

Definizione: Percezione umana innescata da un evento che mina la sicurezza del soggetto
Termine individuato: Libro.

Definizione: evento rischioso che può ledere alla incolumità fisica o mentale di una persona
Termine individuato: Libro.

Definizione: situazione che può arrecare danno
Termine individuato: Manuscritto.

Definizione: evento che rappresenta un rischio per l'integrità di un altro evento, oggetto o persona
Termine individuato: Libro.

Definizione: rischio, minaccia
Termine individuato: Libro.

Definizione: Situazione generica in cui una persona, animale o cosa non vorrebbe ritrovarsi onde evitare una improvvisa riduzione delle proprie aspettative di vita.
Termine individuato: Scrittura.

Definizione: Situazione o sensazione di minaccia
Termine individuato: Libro.

Definizione: Situazione che attiva un meccanismo di difesa per la tua incolumità
Termine individuato: Libro

Definizione: Percezione di una situazione di manato confort in cui l'individuo si sente sotto attacco ed è pronto alla fuga
Termine individuato: Manato

Definizione: È una situazione spaventosa e ansiosa che può comportare ad avvenimenti molto brutti.
Termine individuato: Libro.

Definizione: situazione che mette a rischio l'incolumità di un individuo
Termine individuato: Libro.

Definizione: Situazione o sentimento che provoca insicurezza
Termine individuato: Libro.

Definizione: minaccia
Termine individuato: Libro.

Definizione: situazione o sentimento provato da una persona di insicurezza, instabilità e paura
Termine individuato: Libro.

Definizione: è in una situazione in cui un individuo teme per la sua incolumità in determinate circostanze
Termine individuato: Libro.

Definizione: Contesto che mina la sicurezza o l'integrità di qualcosa
Termine individuato: Manipolazione delle informazioni.

Definizione: Situazione in cui la propria o altrui incolumità è a rischio.
Termine individuato: Libro.

Definizione: Situazione in cui l'incolumità fisica o psicologica è minacciata
Termine individuato: Libro.

Definizione: situazione che può provocare sofferenza
Termine individuato: Libro.

Definizione: situazioni in cui viene messa a rischio la vita di un individuo
Termine individuato: Libro.

Definizione: situazione in cui si rischia di subire una qualche forma di danno
Termine individuato: Libro.

Definizione: percezione di una situazione di minaccia
Termine individuato: Storia.

Definizione: situazione di rischio
Termine individuato: Libro.

Definizione: situazione in cui si teme di essere esposti a danni fisici o morali
Termine individuato: Libro.

Definizione: E' una caratteristica che definisce situazioni che possono portare a un danno dell'individuo
Termine individuato: Libro.


--------------------------PROSSIMO TERMINE--------------------------


Definizione: Strategia di ricerca nello spazio degli stati
Termine individuato: Libro.

Definizione: Strategia di ricerca che permette di stimare il costo che separa la soluzione attualmente selezionata dall'obbiettivo da raggiungere. Permette di scegliere la strada più promettente per proseguire la ricerca
Termine individuato: Libro.

Definizione: regola che permette di approssimare una soluzione ottima a un problema
Termine individuato: Libro.

Definizione: Funzione che stima la distanza dallo stato attuale allo stato obiettivo.
Termine individuato: Libro.

Definizione: Strategia adottata durante la risoluzione di un problema al fine di raggiungere la soluzione in maniera più rapida ed efficiente.
Termine individuato: Libro.

Definizione: Funzione per approssimare un comportamento
Termine individuato: Libro.

Definizione: ipotesi assunta nella ricerca scientifica e metodologia adottata
Termine individuato: Libro.

Definizione: Metodologia di ricerca di fatti o verità
Termine individuato: Manoscritto.

Definizione: Metedologia per trovare soluzione migliore rispetto al problema dato
Termine individuato: Manoscritto.

Definizione: Criterio per stimare la bontà di un percorso scelto da un algoritmo
Termine individuato: Libro.

Definizione: Una tecnica che può essere utilizzata per ottimizzare, migliorare o semplificare un qualche tipo di problema matematico o algoritmico
Termine individuato: Manuscritto.

Definizione: criterio in base a cui un processo decisionale, spesso un algoritmo, è in grado di scegliere tra possibili alternative quella migliore
Termine individuato: Manuale.

Definizione: Misura utilizzata per stimare la bontá di una scelta ai fini di raggiungere un goal
Termine individuato: Libro.

Definizione: regola da utilizzare per semplificare la risoluzione di un problema
Termine individuato: Libro.

Definizione: linea guida
Termine individuato: Libro

Definizione: Regola per aiutare a prendere decisioni
Termine individuato: Libro.

Definizione: parte della scienza che ha come oggetto la ricerca tramite stima
Termine individuato: Libro.

Definizione: Regola stipulata in quanto direttrice (e metodo di valutazione) di una ricerca di un risultato dato un problema preso in considerazione.
Termine individuato: Libro.

Definizione: Assunzione di fatti nell'ipotesi di lavoro che guidano il processo
Termine individuato: Manoscritto.

Definizione: Stima di un costo utile a guidare un processo di decisone
Termine individuato: Libro.

Definizione: È un criterio che viene utilizzato come stima in dei calcoli.
Termine individuato: Manoscritto.

Definizione: regola per semplificare e ottimizzare la soluzione di un problema
Termine individuato: Libro.

Definizione: Approccio di problem solving
Termine individuato: Manoscritto.

Definizione: insieme di strategie
Termine individuato: Libro.

Definizione: metrica usata per guidare una strategia
Termine individuato: Libro.

Definizione: insieme di strategie da utilizzare come linee guida
Termine individuato: Libro.

Definizione: Approccio alla ricerca basato sull'evidenza empirica e sull'intuizione
Termine individuato: Manoscritto.

Definizione: Funzione utilizzata per stimare la distanza dallo stato attuale al goal.
Termine individuato: Libro.

Definizione: Criterio utilizzato al fine dell'ottenimento di un determinato obiettivo
Termine individuato: Libro.

Definizione: scorciatoia mentale utilizzata per risolvere problemi complessi
Termine individuato: Libro.

Definizione: stima che viene utilizzata per calcolare i costi più ottimali nella ricerca di soluzioni algoritmiche nel campo informatico


Termine individuato: Manuale.

Definizione: approssimazione fatta rispetto a un insieme di strategie o un comportamento reale, tipicamente seguita per ottenere una semplificazione
Termine individuato: Libro.

Definizione: funzione che permette di calcolare un risultato che dovrà poi essere validato
Termine individuato: Manoscritto.

Definizione: un insieme di metodi di ricerca che facilitano la scoperta delle cose precedentemente sconosciute
Termine individuato: Libro.

Definizione: strategia o procedimento per ricercare elementi pratici o teorici per risolvere un problema
Termine individuato: Libro.

Definizione: E' un valore di stima per difetto
Termine individuato: Manoscritto.


--------------------------PROSSIMO TERMINE--------------------------

**Output visualization**

In [ ]:
original_terms = ["pantalone","microscopio","pericolo","euristica"]

for index,group in enumerate(collection):
  print(original_terms[index])
  for term in group:
    print(f"{term}: {group[term]}")
  print("\n----------------------------------------------\n")

pantalone
 libro: ['P1', 'P21']
 manzo: ['P2', 'P5', 'P6', 'P12', 'P13', 'P33', 'P35', 'P39', 'P40']
 libro.: ['P3', 'P20', 'P24', 'P25', 'P26']
 manoscritto.: ['P4', 'P7', 'P9', 'P10', 'P11', 'P14', 'P22', 'P27', 'P36', 'P38']
 manufatto.: ['P8', 'P34']
 manipolazione delle onde sonore.: ['P15', 'P17', 'P28', 'P29']
 manzo.: ['P16', 'P23', 'P37']
 abbigliamento.: ['P18']
 manipolazione di frequenze d'onda, ampiezze e timbri.: ['P19']
 manica

1. definizione generale: una parte di un indumento che copre una parte del corpo., definizione2: struttura di supporto per il tessuto in un capo di abbigliamento., definizione3: elemento di un indumento che si estende dalla parte superiore alla parte inferiore., definizione4: sezione di un indumento progettata per proteggere o coprire una parte del corpo., definizione5: elemento di un indumento che si estende dalla spalla alla gamba.

2. definizione più specifica: una sezione di un indumento che copre le gambe., definizione2: struttura di supporto specifica per le gambe in un indumento., definizione3: elemento di un indumento che si estende dalla parte superiore alla parte inferiore, specificamente le gambe., definizione4: sezione di un indumento progettata per coprire le gambe., definizione5: elemento di un indumento con due canali di tessuto per le gambe.

3. termine: manica

il termine "manica" è quello che accomuna semanticamente tutti i termini derivati dalle definizioni, poiché si riferisce specificamente alla parte di un indumento che copre le gam: ['P30']
 manipolazione.: ['P31']
 manipolazione delle gambe.: ['P32']

----------------------------------------------

microscopio
 manuscritto.: ['P1']
 manoscritto.: ['P2', 'P3', 'P7', 'P8', 'P10', 'P13', 'P14', 'P15', 'P19', 'P21', 'P22', 'P24', 'P25', 'P27', 'P29', 'P34', 'P35', 'P36', 'P37', 'P38']
 libro.: ['P4', 'P5', 'P9', 'P11', 'P12', 'P18', 'P20', 'P23', 'P26', 'P28', 'P32', 'P39']
 manifattura.: ['P6']
 manuscrito.: ['P16']
 manipolatore microscopico.: ['P17']
 manufatto ottico

1. definizione generale: un oggetto o dispositivo realizzato con materiali e tecnologie specifiche.
   termini: manufatto, oggetto, dispositivo, realizzato, materiali

2. definizione più specifica: un dispositivo realizzato con lenti per ingrandire oggetti.
   termini: dispositivo, realizzato, lenti, ingrandire, oggetti

3. definizione ancora più specifica: un macchinario dotato di lenti per ingrandire un oggetto.
   termini: macchinario, lenti, ingrandire, oggetto, dotato

ingredienti: macchinario, lenti, ingrandire, oggetto, dotato

il termine che li accomuna semanticamente: macchinario

termine: macchinario
: ['P30']
 libro: ['P31']
 manipolatore: ['P33']

----------------------------------------------

pericolo
 libro.: ['P1', 'P3', 'P6', 'P7', 'P8', 'P9', 'P10', 'P11', 'P12', 'P14', 'P15', 'P17', 'P18', 'P20', 'P23', 'P24', 'P25', 'P26', 'P27', 'P28', 'P30', 'P31', 'P32', 'P33', 'P34', 'P36', 'P37', 'P38']
 storia.: ['P2', 'P35']
 libro: ['P4', 'P5', 'P21']
 manoscritto.: ['P13']
 manuscritto.: ['P16']
 scrittura.: ['P19']
 manato: ['P22']
 manipolazione delle informazioni.: ['P29']

----------------------------------------------

euristica
 libro.: ['P1', 'P2', 'P3', 'P4', 'P5', 'P6', 'P7', 'P10', 'P13', 'P14', 'P16', 'P17', 'P18', 'P20', 'P22', 'P24', 'P25', 'P26', 'P28', 'P29', 'P30', 'P32', 'P34', 'P35']
 manoscritto.: ['P8', 'P9', 'P19', 'P21', 'P23', 'P27', 'P33', 'P36']
 manuscritto.: ['P11']
 manuale.: ['P12', 'P31']
 libro: ['P15']

----------------------------------------------